### ISSUE TITLE
Treure punts de vida a l'enemic 

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#101]
Estimació: 1.5h

Condició de finalització: Quant estigui implementat la gestió de fer dany a l'enemic

user story:

**Comment by casals90** [comment]
@DCorto  ja pots validar!

He fet que quant dispares i fas atack melee li envia el dany corresponent (segons arma o melee) a una funcio de prova que esta al script AI.cs de la carpeta Enemic, ens haurem de posar d'acrod amb @MarcSanchez per posar els noms correctes al player i al enemic per enviar els danys!

**Comment by dcorto** [comment]
Ok, perfecta la funcionalidad.
