### ISSUE TITLE
Permetre que el jugador pugui canviar l'arma 

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#103]
Estimació 3h

Condició de finalització: Que el player pugui canviar l'arma mitjançant una tecla

user story: 21

**Comment by casals90** [comment]
@DCorto  El canvi d'arma està desenvolupat a nivell a lògic!, falta nomes esperar tots els models. (Sprints futurs)

**Comment by dcorto** [comment]
Ojo @casals90  -> "Condició de finalització: Que el player pugui canviar l'arma mitjançant una tecla". ¿¿Y si haces que salga un cubo de diferentes colores mientras esperas los mesh?! Así se verá mas avanzada. Es decir colocar en el centro de la pantalla, abajo un cubo como si fuera el mesh definitivo. Pero así se ve que realmente hay algo que cambia. Probando no he visto la diferencia de apretar las teclas 1,2,3,4 para cambiar entre armas :(

Si acaso luego lo hablamos y vemos! :)

**Comment by ghost** [comment]
Podrias  implementar, como bien dice david, un mesh base y el disparo mismo a baja escala mientras yo me ocupo de la animacion y carlos del mesh, intentare que este todo para mañana. Pero asi te ahorrarias tiempo.

**Comment by casals90** [comment]
@DCorto  Ara tinc l'arma 1 (que he eliminat el braç i nomes es veu unt ros de l'arma) i l'arma 2 que és un cub i l'arma 3 que es una esfera. Ara es veu el canvi. Quan puguis valdia-ho.
Merci!

**Comment by dcorto** [comment]
Vale, se ve el cambio de arma, está perfecto. Ahora se ve que realmente se realiza un cambio entre los tipos disponibles. Pero hay el bug #155. Te lo he abierto y asignado para el Sprint 3. Sólo falta que indiques la estimación.
