### ISSUE TITLE
Programar que l'usuari pugui fer saltar el personatge

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#11]
Estimació 2 hores

Finalització: Quant l'usuari pugui fer saltar el personatje

**Comment by dcorto** [comment]
@casals90 verifica lo siguiente: 

![screenclip](https://f.cloud.github.com/assets/5486937/1301026/2eb956da-311c-11e3-842b-4c811936bfb3.png)

Linea 32 archivo "FPSInputController.cs"

Está saltando con el input definido como "Jump" y debería usar un input llamado "Saltar" definido en la Wiki https://github.com/eloipuertas/ES2013Dimarts/wiki/Controles

**Comment by dcorto** [comment]
En el último commit para probar, te he modificado la linea 32 del archivo mencionado para qué funcione con los mapeos de Inputs que hemos definido con el equipo de menú (Equipo E)

**Comment by dcorto** [comment]
El personaje ya salta!

**Comment by casals90** [comment]
El personatje salta amb el boto espai i funciona correctament
