### ISSUE TITLE
Estado del brazo melee al inicio del nivel

### ISSUE THREAD

**Issue by dcorto** [eloipuertas/ES2013Dimarts#117]
Aquí se puede ver el bug:

Cuando cargas la escena:

![hand_default](https://f.cloud.github.com/assets/5486937/1355973/aa94397e-376f-11e3-9022-025dc967b690.png)

Después del primer ataque:

![hand_afterfirstattack](https://f.cloud.github.com/assets/5486937/1355981/bf8e3bd6-376f-11e3-8d00-3a3425af504e.png)

Para estar bien, cuando se carga la escena debería aparecer el brazo cómo en la segunda captura, es decir, es su estado de "reposo" y no completamente desplegado.

Estimación de esfuerzo: 1h

Condición de finalización: Cuando el brazo se vea en la posición de reposo inicialmente.

**Comment by dcorto** [comment]
@Amestrmu7 quizás necesites participar tú también. Valora el problema a ver si hay que cambiar el modelo o es tema exclusivamente de @casals90

Merci!

**Comment by ghost** [comment]
El estado inicial de la animación es el brazo doblado, simplemente se tendria que mirar de triguear el brazo una vez en la precarga para que lo dejara en su posición. Tambien se deberia mirar un poco el funcionamiento de las animaciones en unity @casals90 .

**Comment by dcorto** [comment]
Vale gracias @Amestrmu7. :)

**Comment by casals90** [comment]
@DCorto  bug corregit. 
He fet que nomes s'activa el braç a lhora de fer l'atac, la resta d'estona queda desectivat!

Apunt x validar!

**Comment by casals90** [comment]
@DCorto  Perdona, l'ultima versio penjada a l'inici esta desactivat, i s'activa un cop fas el primer atac melee, i despres es mante activat, pero a una posició on no es veu a la càmera!

**Comment by dcorto** [comment]
Podemos dar por cerrado el bug pues, acabo de probarlo y funciona perfecto. :)
