### ISSUE TITLE
Animación del brazo derecho con la pistola (Recarga/cambio de arma)

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#124]
IMPORTANTE: Esta animación sera la misma tanto para la recarga como para el cambio de arma.
- La animación concluye con éxito una recarga de la pistola
- Los usuarios aceptan esta animación como buena
  (se tendria que integrar en unity un sonido de recarga y uno de cambio de arma para cada animación: @hiroCat  )

Esfuerzo: 5h

**Comment by ghost** [comment]
La animación la dividire en dos animaciónes: Enfundar y desenfundar. Ambas servirán para las dos cosas.

-Enfundar: On Going
-Desenfundar: Esperando a que @SolrakUndel haga un FIX de la textura. / animación finalizada esperando comentarios.

**Comment by dcorto** [comment]
@Amestrmu7 mañana intentaré ver el estado del modelo y animación para estar al tanto, hoy ya no tengo más tiempo :(

**Comment by dcorto** [comment]
Guay @Amestrmu7 mañana le pego el vistazo. Vamos hablando y vemos si podemos cerrar esto también :+1:

**Comment by ghost** [comment]
Video de todas las animaciones incluidas en el fichero "completo.blend":
- Desenfundar
- Disparo
- Recarga
- Movimiento (EXTRA: no he abierto ni issue para esta)
- Enfundar

http://www.youtube.com/watch?v=CIoaO_tFdOc

**Comment by dcorto** [comment]
Grande! :D:D:D

Aquí el vídeo funcionando algunas ya en Unity -> http://www.youtube.com/watch?v=sEPfdz6L8nI&list=PLTD0-dYPD4flx_6kWtoK8ZqSq8IHyjRb2
