### ISSUE TITLE
crear una llanterna

### ISSUE THREAD

**Issue by hiroCat** [eloipuertas/ES2013Dimarts#127]
esforç: 1

Condició de finalització: el personatge principal pot obrir i tancar una llanterna pressionant la tecla f

**Comment by hiroCat** [comment]
@casals90 m'han dit des del meu grup  que la part de pressionar la tecla ho hauries de fer tu perqué ets de personatge principal , et va molt malament ? sinó miro de fer-ho jo

**Comment by ghost** [comment]
Al ser un elemento unido al personaje principal es trabajo del jordi, de todas maneras no estaria mal mirar de establecer que tipo de luz y como afectara a la escena. (Que dos luces no se solapen y hagan cosas raras etc).

**Comment by casals90** [comment]
@hiroCat  io crec que l'objecte llenterna no l'he de fer, si em passeu l'objecte llanterna amb la llum tal i això jo ho afageixo al player, ja que això ho veig com una pistola o un objecte mes de complement al player.

**Comment by ghost** [comment]
Se especifico que fuera una linterna en si? No quedamos en que le saldria una luz 'foco' en direccion a donde apunte? Sin mesh ni nada   Hay que mirar bien comi se desarrolla este issue

**Comment by hiroCat** [comment]
A veure no m'he expressat be ,si  @Amestrmu7 que la llum en realitat ha de ser nomes un foco ,per ser mes concrets ha de ser una spotlight ,tema incompatibilitats sera la unica llum dinamica de l'escena en principi per tant no hi hauria d'haver cap problema, el que volia @casals90 era la part del trigger que hi ha d'haver dins del personatge per activar-la (la logica de que quan pressionis f s'activi un objecte spotlight x) pero si no ho pots fer tu ja m'espavilare jo

**Comment by dcorto** [comment]
Perdonar que me meta, pero todos tenéis razón, la cosa va así:
@hiroCat  -> crea el objeto luz (un foco, ya que no se ve realmente una linterna)
@casals90 -> hace la lógica de: añadir el input para la linterna y la lógica de encencido y apagado
@Amestrmu7 -> es lo que dices, no lleva "mesh" es un objeto "lógico" digamos, no es nada de blender.

Lo único, que tienen que hablar @hiroCat  y @casals90  para hacerla funcionar bien y ya está :D
