### ISSUE TITLE
Dissenyar enemic 1: Cap/cara (Model+Textura) 

### ISSUE THREAD

**Issue by jxaubet** [eloipuertas/ES2013Dimarts#135]
Estimated effort: 3

Condició de finalització: Crear el model del cap/cara i donar-li textura.

**Comment by jxaubet** [comment]
@Xavier-RF Condició finalitzada.

**Comment by Xavier-RF** [comment]
Issue no tancada, falta la textura ben definida.

Exemple: http://www.drflail.com/images/hopper-textures.jpg

@jordixaubet

**Comment by jxaubet** [comment]
@Xavier-RF Estimated effort (millora del model + nou material/textura): 2

**Comment by jxaubet** [comment]
@Xavier-RF Condicions finalitzades.
