### ISSUE TITLE
Assignar un so per al cop de puny

### ISSUE THREAD

**Issue by hiroCat** [eloipuertas/ES2013Dimarts#142]
esforç: 2

Condició de finalització: quan l'usuari realitzi un cop de puny es dispararà un so

**Comment by ghost** [comment]
Te dejo aqui una web que no tiene que ver mucho para esta issue pero te sera útil:

http://footagecrate.com/

http://soundbible.com/1920-Minigun.html

(http://www.youtube.com/watch?v=L8GQKdNXHpc)
