### ISSUE TITLE
Creación de la textura del Power-Up de la munición

### ISSUE THREAD

**Issue by Nekoshido** [eloipuertas/ES2013Dimarts#152]
Estimación de esfuerzo: 3

Condición de finalización: Creación y aplicación de la textura para el power-up de la munición

**Comment by Ooin** [comment]
Cal que exportis el power-up a fbx i que el posis a lloc per que el pugui testejar.
Aquesta issue i la #144 no son practicament iguals?

**Comment by Nekoshido** [comment]
Això és la textura ( el .png), la 144 es l'objecte en si. Suposo que falta crear una issue de creació de textures o algo així. Ja està el .fbx perquè el puguis testejar
