### ISSUE TITLE
Destruir Barril

### ISSUE THREAD

**Issue by AlcoholNahMas** [eloipuertas/ES2013Dimarts#153]
Estimación de esfuerzo: 5

Condición de finalización: Fer un canvi de barril quan aquest es detrueixi, aquest no te animació es simplement fer el canvi.

Tags: 
Barril - per el barril en bon estat.
DestroyBarril - per el barril un cop destruit.

**Comment by Ooin** [comment]
Caldria que posesis els scripts i tot al seu lloc de la carpeta UNITY per que ho pugui testejar.

**Comment by Ooin** [comment]
No se exactament com ho he de posar per poder testejar-ho. Siusplau explica-m'ho i aixi ho acabo d'una vegada.
Quan poso els dos barrils en pantalla no em surt cap textura.
