### ISSUE TITLE
Cuando el personaje se agacha, el modelo del arma se "comprime"

### ISSUE THREAD

**Issue by dcorto** [eloipuertas/ES2013Dimarts#155]
Estimación de esfuerzo: 2h

Condición de finalización: Cuando el arma no cambie de tamaño al estar agachado.

**Comment by casals90** [comment]
Estimació: 2h

**Comment by dcorto** [comment]
@casals90 thanks. Estimación añadida.

**Comment by dcorto** [comment]
Correcto, los modelos no se comprimen pero hay que arreglar lo siguiente -> https://github.com/eloipuertas/ES2013Dimarts/issues/231 lo antes posible.
