### ISSUE TITLE
Programar la logica de quant l'usuari dispari al barril

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#156]
Estimacio: 1h

Condicio de finalització: Que quant l'usuari dispari al barril, @AlcoholNahMas  gestioni quant ha de fer el canvi pel barril destrosat

**Comment by casals90** [comment]
@DCorto  ja esta desenvolupat.
A l'escenari de prova hi ha una capsula que si la dispares 4 cops canvia per un cilindre.

També ha estat testejat amb el barril "final" per @AlcoholNahMas  i funciona!

Quant puguis valida!

**Comment by dcorto** [comment]
Vale Jordi, después de clase lo valido. Great work!
