### ISSUE TITLE
Contador de munición en cargador y  munición total no se actualiza

### ISSUE THREAD

**Issue by dcorto** [eloipuertas/ES2013Dimarts#172]
Estimación de esfuerzo: 1h

Condición de finalización: Una vez se actualice el HUD de munición en cargador y total correctamente en la pistola.

**Comment by casals90** [comment]
@Dabami  Ia he arreglat les variables que em parlat perquè puguis agafar les variables mes facilment i puguis mostrar correctament!

(Un detall es que les bales que hi ha al inici al carregador, no les conto de les bales totals, ja que cada cop nomes s'actualitza bales actual carregador, i es a lhora de carregadr on on resto les bales que falten al caregador de les totals de l'arma. Si vols que ho faci d'una altre manera ja em diras).

**Comment by dcorto** [comment]
@Dabami  lo que comenta @casals90  sobre el número de balas y tal, es lo que está comentado también aquí: https://github.com/eloipuertas/ES2013Dimarts/issues/173#issuecomment-27474448

**Comment by dcorto** [comment]
@Dabami  @Akrox  ¿hacemos una prueba en una branch para el caso? Decirme algo

**Comment by casals90** [comment]
@Dabami Ja esta tot correcte tal com ho vam parlar!!
