### ISSUE TITLE
Si pulsas recargar 2 o más veces seguidas no dispara

### ISSUE THREAD

**Issue by dcorto** [eloipuertas/ES2013Dimarts#173]
Estimación de esfuerzo: 2h

Condición de finalización: Cuando puedas seguir disparando si has pulsado recargar 2 o más veces sin disparar antes.

Si pulsas varias veces repetidas la tecla de recargar el arma, no dispara más hasta que vuelves a seleccionar otra arma y vuelves a la arma de nuevo.

**Comment by casals90** [comment]
Estimació: 2h

**Comment by dcorto** [comment]
@casals90 estimación añadida. Te valido lo antes posible.

**Comment by dcorto** [comment]
@casals90 perfecto, esto queda fixed!

Hay que tener en cuenta, que cuando se empieza con la pistola, tienes las 100 balas cargadas más las 10 del cargador, por lo que tienes en total 110 disparos posibles. Yo lo veo correcto así como está implementado :)
