### ISSUE TITLE
El valor del escudo llega a valores negativos

### ISSUE THREAD

**Issue by dcorto** [eloipuertas/ES2013Dimarts#174]
Estimación de esfuerzo: 0.5h

Condición de finalización: Cuando el valor del escudo no se decremente en menos de 0

**Comment by casals90** [comment]
Estimació : 0.5h

**Comment by casals90** [comment]
@DCorto  bug corregit! Ja pots validar!

**Comment by dcorto** [comment]
Has hecho el commit a master nanu :P Fix it!

**Comment by eloipuertas** [comment]
Violadors del master!
El dia 30/10/2013 23:42, "D. Corto" notifications@github.com va escriure:

**Comment by dcorto** [comment]
Va on fire tonight @casals90 :beers:

**Comment by dcorto** [comment]
@casals90 vale, ya he visto el commit en la branch A correcto y he revertido el commit de master. Mañana te valido el issue. Demasiadas emociones fuertes por hoy :P.

@eloipuertas master des-violado ^^!

**Comment by casals90** [comment]
jajaj despres de 2 exams de VA i ES ja no se on soc xdd arregalt!

**Comment by dcorto** [comment]
@casals90, cuando recibes un daño de 15, el escudo se reduce a 0 con el primer impacto. No es correcto ese funcionamiento. Debe reducirse hasta 0 en función del daño recibido.

**Comment by casals90** [comment]
@DCorto  Ara ja esta arreglat!! quant puguis ja pots validar!
