### ISSUE TITLE
Animación de interacción con botones/enemigos/etc (brazo izquierdo)

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#176]
Condición de fin:
- La animación se dará por finalizada cuando se vea realista 
- Este implementada correctamente en unity sin ningún problema.
  (Se trabajará encima del brazo de "atac melee", brazo izquierdo)

Esfuerzo : 2 horas

**Comment by dcorto** [comment]
Las 2 animaciones nuevas que sustituyen el brazo izquierdo por ataques por el arma son impresionantes :)
