### ISSUE TITLE
Improve texture of "prototype v1 of Gun"

### ISSUE THREAD

**Issue by SolrakUndel** [eloipuertas/ES2013Dimarts#180]
Estimation: 6 h

Finishing condition: The texture of the first prototype of the Gun must have been improved.

**Comment by dcorto** [comment]
![screenclip](https://f.cloud.github.com/assets/5486937/1468830/1ddc3cc4-4599-11e3-8d04-0fb2466ad000.png)
![screenclip2](https://f.cloud.github.com/assets/5486937/1468831/1ddecf5c-4599-11e3-8bc7-93bdb753f91b.png)

Gran trabajo @SolrakUndel
