### ISSUE TITLE
Create the "prototype v1 of the Rifle"

### ISSUE THREAD

**Issue by SolrakUndel** [eloipuertas/ES2013Dimarts#181]
Estimation: 2 hours

Finishing condition: The model of the first prototype of the Rifle must have been done, materials and textures included.

**Comment by dcorto** [comment]
Me gusta mucho la primera versión del rifle @SolrakUndel 

¡Gran trabajo!

![screenclip](https://f.cloud.github.com/assets/5486937/1535534/7112c7ce-4ca5-11e3-9a17-13017cc01ddb.png)

**Comment by dcorto** [comment]
@Amestrmu7 creo qué ya puedes animar a esta preciosidad :D
