### ISSUE TITLE
 Implementar el 'usar' amb la tecla E 

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#182]
Estimacio: 2.5h

Condició de finalització: Quant la lògica de apretar la tecla 'E' estigui implementada

**Comment by casals90** [comment]
Lògica implementada.

A l'espera de @Amestrmu7  tingui l'animació, i @AlcoholNahMas tingui el boto creat i el script del boto desenvolupat.

**Comment by dcorto** [comment]
Ok, antes de cerrar, veamos que: la animación se realiza también, es parte de la lógica.

**Comment by casals90** [comment]
@DCorto PArt lògica implementada, animacio afegida i script del boto de @AlcoholNahMas  fet.

**Comment by dcorto** [comment]
@casals90 la lógica y la animación funcionar perfectamente, lo he probado en la integración además.

**Comment by casals90** [comment]
Perfecte!!
