### ISSUE TITLE
Implementar dany per gravetat 

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#183]
Estimació: 2h

Condició de finalització: Quant la lògica del dany segons l'altura en que està el player estigui implementada

**Comment by casals90** [comment]
@DCorto  dany per gravetat implementat! Ja pots validar kuan vulgui!

observacio: he fet que segons l'alutra que esta quant cau li moltiplico una constant, ho dic x si vols acabar d'ajustar una mica els paràmetres. Són a l'script FPSWalker les variables ConstantDamageFall i FallingDamageThreshold.

una altre cosa, es que he modificat l'escenari, i inicialment el player cau de una altura i també he posat dues rampes x provar el dany!

**Comment by ghost** [comment]
Perfecto jordi! Hoy nos lo miramos y vamos ajustando el daño para hacerlo mas preciso. GJ!

**Comment by dcorto** [comment]
@casals90 nice done, está muy chulo :)

**Comment by dcorto** [comment]
Te reabro la issue por este bug -> https://github.com/eloipuertas/ES2013Dimarts/issues/239

**Comment by casals90** [comment]
@DCorto  dany per gravetat implementat! Quant puguis valida-ho! Gràcies!!

**Comment by dcorto** [comment]
@casals90  :+1:
