### ISSUE TITLE
Botó shift per caminar 

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#184]
Estimació: 3h

Condició de finalització: Qunat la lògica de que l'usuari apreti el boto 'shift' que el player camini estigui implementada

**Comment by casals90** [comment]
@DCorto  Boto shift per caminar implementat! ja pots validar quant vulguis!!

Si alhora de validar creus que ha danar mes rapid o mes lent, ajustaho tu mateix.

Son les variables: SpeedRun i SpeedWalk

**Comment by ghost** [comment]
Cuanta cañana en tan poco tiempo! Goodjob! Keep working!

**Comment by dcorto** [comment]
@casals90 nice, lo valido lo antes posible.

**Comment by dcorto** [comment]
A ver, es correcto el funcionamiento, pero te has cepillado el input "Escape" para el menú de pausa.
![screenclip](https://f.cloud.github.com/assets/5486937/1452793/fecc317a-42de-11e3-80fd-108d0cc6f5fd.png)

**Comment by dcorto** [comment]
El commit anterior fixea lo comentado en https://github.com/eloipuertas/ES2013Dimarts/issues/184#issuecomment-27557038

**Comment by dcorto** [comment]
Te reabro la issue, por este bug -> https://github.com/eloipuertas/ES2013Dimarts/issues/239

**Comment by casals90** [comment]
@DCorto  ia pots validar quant puguis

**Comment by dcorto** [comment]
@casals90  :+1:
