### ISSUE TITLE
Hacer un ataque de melee en la dopesheet de la pistola con la pistola (no con el brazo)

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#189]
- La animación de la pistola ahora incorporara un ataque melee diseñado especialmente para cuando se lleve la pistola seleccionada. 
- Se debe eliminar el brazo del ataque melee y gestionar en unity que la animación de melee sea ahora con el brazo izquierdo que esta junto al arma (pistola) y no el que va suelto.

Condición fin:
- La animación parece real y es aceptada como ataque melee.
- Las animaciones que habian estan bien redistribuidas y ordenadas para su buen exporte a unity
- La animación puede ser reproducida correctamente en Unity

Esfuerzo: 8 horas. (se ha de Re-Animar una parte de la pistola y hacer este ataque)

@hiroCat : Se te requiere en esta issue para poder "cerrar" el story correspondiente (sonido de puñetazo, luces, etc)

**Comment by ghost** [comment]
Voy a crear dos tipos de ataques meelee para poder combinarlos y que quede mas "real". En el codigo se tendrá que hacer un random entre dos numeros al azar y seleccionar una o la otra animación.

**Comment by ghost** [comment]
310 - 334 : ataque con culata en horizontal
354 - 376 : ataque con la culata en diagonal

Esperando aceptación

**Comment by dcorto** [comment]
@Amestrmu7  me gustan mucho las animaciones de ataque melee :D:D:D:D
