### ISSUE TITLE
Animación de los huesos sobre el brazo izquierdo del personaje principal

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#2]
As a main character I want to do a melee attack.

```
 - Animación de los huesos sobre el brazo izquierdo del personaje principal
```

Estimación: 4 horas
Condició d'acabada: La animación se mueve y da la sensación de dar un puñetazo.

**Comment by ghost** [comment]
Updated :+1: La animación funciona, falta acelerarla y editar la rotación de los huesos para hacerla mas realista.
Esperando feedback de compañeros. (Agradeceria algun comentario en este issue para ir perfeccionando la animación)

Feedback: 

-D. Camacho: Bien implementado.

Estimación: 2 horas

**Comment by ghost** [comment]
Finished: Animación acabada, falta el feedback de los demas miembros.
/\*  Esta animación tiene un "delay" de uso, he animado creyendo conveniente que el puñetazo no es "spam"eable, es decir entre uso y uso tardaremos x segundos.  */

En espera de feedback.

Estimació: 0 horas

**Comment by dcorto** [comment]
Vale Alfonso, good job! :+1:

**Comment by dcorto** [comment]
@casals90 la ha probado hoy en el proyecto y la he verificado, realmente da la sensación de puñetazo! :ok_hand: 

![image](https://f.cloud.github.com/assets/5486937/1293234/ae570948-3061-11e3-956a-c7af7c543db6.png)
