### ISSUE TITLE
Diseño: Estética del Menu Principal

### ISSUE THREAD

**Issue by degel99** [eloipuertas/ES2013Dimarts#20]
Estimated effort : 2h
Product Backlog: 11. As a user I want to start a new game or continue at the beginning of the last level I played.
Condición de finalización: Mejora de la visualización del fondo de la escena del menú de inicio.

**Comment by Akrox** [comment]
Done

**Comment by Akrox** [comment]
Reabro como mejora a petición del artista.

**Comment by Akrox** [comment]
Done
