### ISSUE TITLE
Animación de "caminar" (tecla shift)

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#205]
Condición de acabado: Animación de caminar es real y la exportación es satisfactoria.

Esfuerzo: 1 hora.

**Comment by ghost** [comment]
En la animación resulta cortada y se "filtra" con la de caminar/correr.
necesito ayuda de @casals90  para poder acabar este issue (importación a unity incluida)

**Comment by ghost** [comment]
Esta issue debe ser enlazada con la #230 ya que al tener la prioridad podre enlazar perfectamente las animaciones (la condición de finalizado esta completada ya que la lógica/animación esta hecha, falta la integración efectiva a unity @DCorto  (esta parcialmente))

**Comment by dcorto** [comment]
Vale, lo validaré esta noche.

**Comment by dcorto** [comment]
La animación funciona correctamente cuando el personaje camina.
