### ISSUE TITLE
Assignar un conjunt de sons per a la pistola 

### ISSUE THREAD

**Issue by hiroCat** [eloipuertas/ES2013Dimarts#215]
esforç:2

condicio finalitzacio: quan el fet de disparar i recarregar produeixi un so

**Comment by ghost** [comment]
@hiroCat , he encontrado la próxima parte de la pistola que deberías implementar (el fogonazo), trata sobre muzzles . Esta muy bien explicado!
te lo dejo por aquí por si le quieres echar un ojo

http://forum.unity3d.com/threads/186678-Muzzle-Flash-for-auto-guns

http://www.youtube.com/watch?v=viv8ma7HpX0

**Comment by hiroCat** [comment]
s'haurien de definir coses , per exemple jo pensava que la pistola era de raigs laser ( per tema ser un robot i tal ) per tant assumeixo que no i parteixo de que es "normal"  correcte ?

**Comment by dcorto** [comment]
Sí es "normal" no hay rayos láser por ahora :P

**Comment by ghost** [comment]
Una vez tengas un fogonazo de pistola, con que lo pongas lila/azul cualquier cosa fosforita ya parecera un ataque alien.

**Comment by hiroCat** [comment]
quan dura l'animació de recarregar la pistola ? (tema temps) per a triar un so un altre

**Comment by dcorto** [comment]
@hiroCat mira lo que hay en master, la animación de recarga de momento es la misma que la que ya hay desarrollada. Exactamente no se la duración ahora mismo. ¿Puedes mirarlo tú mismo?

**Comment by hiroCat** [comment]
si es la del master si ! nose perqué pensava que s'havia de canviar, endavant doncs .

**Comment by dcorto** [comment]
Estamos trabajando en nuevas animaciones, pero la de recargar se mantiene igual :)
