### ISSUE TITLE
Comprova maxim de triangles d'una escena en unity

### ISSUE THREAD

**Issue by jme88** [eloipuertas/ES2013Dimarts#233]
Condició de finalització: Comprovar quin es el numero maxim de triangles que admet una escena de unity i comprovar quins efectes produeix superar aquest numero i com es pot solucionar.

Estimació: 4h

**Comment by hiroCat** [comment]
a la aula IA amb tres vegades els models que has creat no es nota gens el lag , s'ha de dir que les grafiques són nvidies gtx 570
![testing2](https://f.cloud.github.com/assets/5578838/1543331/c56284cc-4d54-11e3-977d-e786a5ddc5a6.PNG)
![testing](https://f.cloud.github.com/assets/5578838/1543332/c5849530-4d54-11e3-9239-2ab24b588fdc.PNG)

estaria bé que algú amb una grafica menys potent o provés , jo ho intentaré provar als pcs de peixeres tot i que allí tarda molt en instalar-se ( el unity)

**Comment by hiroCat** [comment]
s'ha de dir que si augmentes fins a molt el con de la llanterna i et poses des de fora a fer una vista més general es nota una mica que comença a tenir cert lag

**Comment by dcorto** [comment]
Los de la IA además son i7 :P Pero tela con la prueba
