### ISSUE TITLE
Des-implementar el FPSWalkerEnhanced.cs (No es compatible con las plataformas)

### ISSUE THREAD

**Issue by dcorto** [eloipuertas/ES2013Dimarts#239]
Estimación de esfuerzo: 3h

Condición de Finalización: Las funcionalidades de caminar y daño por gravedad están implementadas y el player es compatible con las plataformas móviles.

@casals90 el FPSWalker no se puede usar. Hay que usar el Character Motor y el FPS Input. Por lo que la funcionalidad de caminar y el daño de caída no están funcionando.

Por defecto el Motor y el Input están en JavaScript pero aquí (http://forum.unity3d.com/threads/64378-CharacterMotor-FPSInputController-PlatformInputController-in-C) los tienes en C#.

![screenclip](https://f.cloud.github.com/assets/5486937/1499000/91373cd2-484b-11e3-9f81-f62749c3b354.png)

Ahora para la integración los he dejado los originales, para que el personaje funcione, aunque no funcione el daño por gravedad y el tema del caminar. 

Voy hacer un merge desde DEV a Grupo-A para que tengas todo lo necesario para trabajar en esto.

**Comment by dcorto** [comment]
@casals90 hay que mirar si el FPS Walker, se puede usar con los 2 scripts anteriores retocandolo un poco, ya que estoy viendo qué otros dev's en general, lo usan bastante. 

Quizás escribiendo un script sencillo aparte para calcular "una caída" es más simple que intentar re implementar todo usando el FPS Walker.

**Comment by dcorto** [comment]
Mira, creo qué ya tengo la idea

Then, when the player hits the ground, you can check if the falling speed is greater than the threshold for causing damage:

if (falling && grounded) {

```
if (maxFall > fallDamageThreshold) {

    BroadcastMessage ("ApplyDamage",damage);

}

falling = false;
```

}

http://forum.unity3d.com/threads/46101-Fall-damage-question

**Comment by casals90** [comment]
Estimacio 3h

**Comment by dcorto** [comment]
@casals90 gracias por la estimación.

**Comment by casals90** [comment]
@DCorto  Desimplementació del FPS walker realitzada correctament! ja pots validar quant puguis

**Comment by dcorto** [comment]
¡Perfecto! :+1:
