### ISSUE TITLE
Evitar que l'usuari es quedi sota les plataformes i les traspassi 

### ISSUE THREAD

**Issue by hiroCat** [eloipuertas/ES2013Dimarts#241]
Estimació: 5h

Condició de finalització: Quant l'usuari no pugui quedar sota la plataforma quant aquesta baixa.

**Comment by ghost** [comment]
Solución propuesta:
- Si el personaje se queda debajo de la plataforma y es "aplastado", se le quitara X vida y será empujado hacia un lado.

**Comment by casals90** [comment]
@DCorto  Estimació i condició de finalització afegida.

**Comment by dcorto** [comment]
@DavidOrlaz alguien del grupo CD se está mirando esto también?!

**Comment by dcorto** [comment]
@DavidOrlaz me puesto en ello y ya lo tengo controlado, por lo menos para la primera plataforma que es la única que a priori te puede "aplastar". 

Voy a grabar una demo y ahora comento.

**Comment by dcorto** [comment]
@Amestrmu7 cuando veas la demo, verás que es mejor que la solución que has propuesto. Aunque parecía más fácil tu solución, nada más lejos de la realidad, con 4 líneas de código he logrado tener algo más bonito :)

**Comment by ghost** [comment]
Ya la he visto, buen trabajo chicos! 
Mi solucion era mas grafics y visualitzacio de dades jajaja pero si asi es mas optimo, GG! 
Nos vemos en el meeting

**Comment by ghost** [comment]
(Pd: ese comentario era sobre las boxes y las paredes, xD lo siento) si ya he visto la solucion, bien hecho!

**Comment by dcorto** [comment]
Demo del fix -> http://www.youtube.com/watch?v=X6_pucKhNb8

**Comment by dcorto** [comment]
Doy por cerrada la issue, además de que el usuario no pueda "traspasar" la plataforma, si queda "aplastado" por ella, le resta una cantidad de vida.
