### ISSUE TITLE
When player jumps over a platform, he goes through platform and remains on floor

### ISSUE THREAD

**Issue by eloipuertas** [eloipuertas/ES2013Dimarts#246]
Estimació: 5h

Condició de finalització: Que quant el player salti a la plataforma, no la travessi.

**Comment by dcorto** [comment]
@DavidOrlaz aunque principalmente tenemos que trabajar los del grupo-A en esta Issue, la asignamos a CD también para trabajar conjuntamente.

**Comment by dcorto** [comment]
@casals90, seguramente solucionando este problema -> https://github.com/eloipuertas/ES2013Dimarts/issues/231 (Generar un character controller correcto que evite penetrar los brazos en los muros) esto lo podamos dar por cerrado también.

**Comment by dcorto** [comment]
La issue #241 (Evitar que l'usuari es quedi sota les plataformes i les traspassi) es idéntica a esta. Ahora hemos solucionado el tema del clipping de los brazos, por lo que la sensación de "saltar" fuera de la plataforma ya no se produce. Sigue pasando lo comentado en la #241, por lo que esta issue la podemos cerrar y centrarnos en la #241 

¿Qué os parece?! @casals90 @Ooin

**Comment by dcorto** [comment]
Issue duplicada #241
