### ISSUE TITLE
You have to be too close to kill an enemy.

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#247]
Maybe increasing collision mesh/area will fix this.

**Comment by Xavier-RF** [comment]
Bug asignat al grup B

**Comment by dcorto** [comment]
@Xavier-RF, el grupo-A también lo asignamos para estar al loro sobre el avance de la issue. @casals90 y @MarcSanchez  trabajarán en ello.

**Comment by dcorto** [comment]
@Xavier-RF como lleváis este tema?! ¿Necesitáis algo del grupo A?

**Comment by Xavier-RF** [comment]
El problema esta en los brazos, que se ponen enmedio y no dejan que el raycast llegue o salga del collider del personaje. Se puede arreglar usando una cosa que se llaman layer masks pero me parece que es un lio bastante importante. 

Como solución por parte de los enemigos he usado el RaycastAll que lanza un raycast y te devuelve todos los elementos que atraviesa. Despues de lanzar el raycast recorres la lista de elementos que se han colisionado buscando el Tag del player o del enemigo.

Ejemplo:
http://docs.unity3d.com/Documentation/ScriptReference/Physics.RaycastAll.html?from=RaycastHit

Para arreglar el disparo del enemigo he modificado la función de disparar que teniamos antes por esta:

```
private void disparar(int distancia,int dmg){
    RaycastHit[] hits;
    hits = Physics.RaycastAll (transform.position, (target.position- transform.position), distancia);; 
    int i = 0;
    while (i < hits.Length) {
        RaycastHit hit = hits[i];
        Debug.Log (hits[i]);
        if (hits[i].collider.tag == "Player"){
            Debug.Log("ataco al player i li faig "+dmg+" punts de dany");
            hit.transform.gameObject.SendMessage("rebreAtac",dmg);
            break;
        }
        i++;
    }
```

}

Poniendolo asi no da ningun problema al disparar por parte de los enemigos. Haria falta que el player hiciera lo mismo para poder matarlos.

@casals90 @DCorto @MarcSanchez

**Comment by Xavier-RF** [comment]
Me aburria un poco y he estado trasteando con el player. Para que funcione el disparo del player hacia el enemigop haria falta modificar codigo en dos sitios:
Para los disparos:

```
    if((Input.GetButtonDown("Disparar")) && (balesCarregador > 0)) {
        balesCarregador = weapons[posWeapon].disparar();
        RaycastHit[] hits;
        hits = Physics.RaycastAll (cam.position, cam.forward, shotDistance);
        int i = 0;
        Debug.Log("Shooting!!!!!");
        while (i < hits.Length) {
            RaycastHit hit = hits[i];
            Debug.Log ("RAYCASTING PASSING THROUGH: "+hits[i].collider.tag);
            if (hits[i].collider.tag == "Enemy"){
                Debug.Log("disparo al enemic i li faig "+actualWeaponDamage+" punts de dany");
                hits[i].transform.gameObject.SendMessage("rebreDany",actualWeaponDamage);
                break;
            }else if(hits[i].collider.tag == "Barril"){
                hits[i].transform.gameObject.SendMessage("rebreTir");
            }else if(hits[i].collider.tag == null){
                break;
            }
            i++;
        }
```

Para el ataque melee:

else if((Input.GetButtonDown("Melee")) && (down == false)) {
            weapons[posWeapon].meeleWeapon();
            RaycastHit[] hits;
            hits = Physics.RaycastAll (cam.position, cam.forward, meleeDistance);
            int i = 0;
            while (i < hits.Length) {
                RaycastHit hit = hits[i];
                Debug.Log (hits[i]);
                if (hits[i].collider.tag == "Enemy"){
                    Debug.Log("ataco al enemic i li faig "+damageMelee+" punts de dany");
                    hits[i].transform.gameObject.SendMessage("rebreDany",damageMelee);
                    break;
                }else if(hits[i].collider.tag == null){
                    break;
                }
                i++;
            }

@casals90 @DCorto

**Comment by dcorto** [comment]
@Xavier-RF buen trabajo! Gracias por comentar los cambios, lo implementaremos tal y como indicas :)

**Comment by dcorto** [comment]
@casals90 tienes en cuenta lo que ha comentado @Xavier-RF?

**Comment by casals90** [comment]
@DCorto  sisi ja ho em parlat a classe avui.

@hiroCat ja he penjat la versio que funciona, si et pots mirar lu del fogonazo k ha kedat enrerra i acabar-ho d'ajustar, xk el problema era que disparava contre el muzzleFlash! merci

**Comment by dcorto** [comment]
@casals90 ok, a ver qué dice @hiroCat sobre este problema y acabamos de matar esto al 100% :)

**Comment by hiroCat** [comment]
"thas problem" resideix en que heu modificat la layer de muzzle flash ( suposo que al modificar el pare i aplicant-lo directament al fills), jo he canviat la layer a default en la teva branca ( @casals90 ) i en principi es veu bé.

Pel tema del dispar i l'efecte en l'enemic ( que no el tapi i tal ) nose si canviant a la layer ignore raycast és igual de efectiu , jo ho he provat i en principi es veu bé i mata l'enemic a certa distancia 

![sin ttulo](https://f.cloud.github.com/assets/5578838/1579960/c75447cc-51ad-11e3-9bcd-8c66e4ad90ee.png)

edit: es veu desplaçat lu del foc suposo que de tan modificar-lo per saber que passava , quan el david pugi el player ho arreglo i ja ta !

**Comment by dcorto** [comment]
@hiroCat por la noche intento subir el player actual de la rama del Grupo-A y así ya podemos seguir debugando en dev. Si @Xavier-RF pudiese poner un enemigo actualizado también entre hoy y mañana podríamos terminar de hacer las pruebas y dar por cerrada la issue :P

Great work!

**Comment by dcorto** [comment]
@hiroCat ya lo tienes en dev todo. Si tienes alguna duda me preguntas. En principio solo es que mires la "posicion" del muzzleflash y light a ver porque salen por encima del arma :( 

Mañana lo comentamos si acaso. Merci

**Comment by dcorto** [comment]
@hiroCat ya tienes integrado el player en el nivel1 y nivel2 de dev para que puedas trabajar en integrar lo que falte de tus desarrollos en él. Gracias.

**Comment by dcorto** [comment]
Esto lo podemos cerrar ya, está corregido el problema :)
