### ISSUE TITLE
Funcionalidad del icono de la linterna

### ISSUE THREAD

**Issue by dabami** [eloipuertas/ES2013Dimarts#255]
Estimated effort: 2 hours

14 - As a user I want to see always my status on screen while I'm playing. 

Condición de finalización: El indicador de la linterna muestra si está encendida o apagada.

**Comment by Akrox** [comment]
Linterna funcionando, no cierro la issue porque queda pendiente modificación de luz de linterna encendida que se realizará en el siguiente sprint como mejora.

**Comment by Akrox** [comment]
Cierro issue porque cumple su condición de finalización, será reabierto el siguiente sprint como mejora de diseño.
