### ISSUE TITLE
Animación personaje principal (Pistola) de recibir daño de un enemigo

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#256]
Condición de finalización:
     - La animación es realista y tiene una velocidad correcta.
     - La animación es completamente funcional en Unity

Estimación: 2h

(@hiroCat, sonido de dolor!)

**Comment by dcorto** [comment]
@Amestrmu7 intento validarlo mañana que hoy no tengo más tiempo, sorry :(

**Comment by dcorto** [comment]
@Amestrmu7 perfecto. Demo -> https://www.youtube.com/watch?v=6waPyh1P8Xc

Sólo falta integrarlo en Unity. ¡Buen trabajo!

¿@hiroCat el sonidito de dolor como lo llevas?

**Comment by hiroCat** [comment]
el so del dolor està fet i implementat des de l'sprint 2, el que passa és que no és del gust de ningú per tant l'estic redissenyant per tercera vegada , quan el tingui fet el passo

**Comment by dcorto** [comment]
@hiroCat cierto!! Es verdad :P

**Comment by dcorto** [comment]
Cumple con las condiciones de finalización y se aprecia claramente el comportamiento cuando el Player recibe daños.
