### ISSUE TITLE
Animación personaje principal (Pistola) de "stand by"

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#259]
Crear una animación para la pistola para cuando no se este tocando el personaje.

Condición:
- La animación es real i tiene sentido
- La animación es exportada a unity y se reproduce correctamente.

Estimación: 3h.

**Comment by ghost** [comment]
@DCorto esta animación ya esta completa. Como la anterior de "recibir daño" mañana la subiré en una escena para ver si todo esta correcto y ya se podría integrar y cerrar. Mañana continuo, deberías mirar si esta bien así o si se tiene que cambiar.
@SolrakUndel @casals90 , tambien necesito que me digáis si esta bien o que veis que puede faltar en TODAS las animaciones de la pistola. Gracias

**Comment by dcorto** [comment]
Para mi está perfecto, junto con la issue #256 que te acabo de validar he creado la demo -> https://www.youtube.com/watch?v=6waPyh1P8Xc

Sólo falta integrarlo en Unity. ¡Buen trabajo!

**Comment by dcorto** [comment]
Cierro la issue, está funcionando perfecto @Amestrmu7 :)
