### ISSUE TITLE
Re-Animar la pistola para que no parezca que "se mueva sola".

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#261]
Condición: 
- La pistola se mueve a la par con la mano/brazo.
- Exportado a unity completo.

Estimación: 5h.

*Lo abro como bug-medium a petición de Eloi

**Comment by dcorto** [comment]
@Amestrmu7 esto verdad qué lo tienes terminado ya?! 

Me he mirado el blender y parece correcto, luego en el meeting lo comentamos para coordinar la re-integrarción en Unity. Te cerraré la issue después de la integración en Unity.

**Comment by ghost** [comment]
Si david, ayer te lo dije de malas maneras y no quedo claro sorry. En una hora hacemos el meeting y comento como lo he arreglado y que he ampliado de las animaciones 
Gracias

**Comment by dcorto** [comment]
@Amestrmu7, ¿verdad qué esto lo tienes implementado ya?

**Comment by ghost** [comment]
@DCorto si, ya tienes preparado la animación. Mañana la integro en una escena para hacértelo mas fácil.

**Comment by dcorto** [comment]
Junto con las otras animaciones que me he mirado, la calidad ha mejorado mucho. Gran trabajo @Amestrmu7.

A ver si hoy con @casals90 las podéis poner todas en Unity y os puedo cerrar las issues.

De verdad, gran trabajo :)

**Comment by dcorto** [comment]
@Amestrmu7 veo todo ok menos la animación de correr, la veo demasiado brusca para mi gusto. Es de la importación seguro ya que en el blender se ve bien, pero en la implementación en Unity ha quedado demasiado tosca. Mañana lo comentamos en persona. :)

**Comment by ghost** [comment]
He editado el correr en unity. Faltaba cuadrar los frames bien!
He actualizado la posición de la mano en la escena y updateado en la wiki los requerimientos!
dejo la foto para la gente que lo necesite:
![image](https://f.cloud.github.com/assets/5486609/1595750/eeb73a34-52ef-11e3-8408-eaad20a5a5ab.png)
PD: ya puedes cerrar el issue si todo pasa el test! :dancers:

**Comment by dcorto** [comment]
Ok, ahora queda perfecto. Gracias :)
