### ISSUE TITLE
Escena de créditos

### ISSUE THREAD

**Issue by camilopalacios** [eloipuertas/ES2013Dimarts#269]
Estimated effort: 3 hours

Backlog: 41. As a user I want to know about the development team with a credits scene.

Condición de finalización: Se muestra correctamente la escena de créditos al pulsar la opción del menú principal.

**Comment by Akrox** [comment]
Escena de creditos funcionando genial, pendiente de inserción de imágenes.

**Comment by camilopalacios** [comment]
Efectivamente señor tester! XD

**Comment by Akrox** [comment]
Incluidas imáneges pendientes en la escena créditos, cierro issue ya que funciona correctamente.
