### ISSUE TITLE
Actualizar la vida.

### ISSUE THREAD

**Issue by dabami** [eloipuertas/ES2013Dimarts#27]
Estimated effort: 2 hours

Backlog: 14. As a user I want to see always my status on screen while I'm playing.

Condición de finalización: La vida se actualiza cuando es modificada.

**Comment by dabami** [comment]
La vida ya se actualiza por cada frame.

**Comment by Akrox** [comment]
Cumple su condición de finalización, se actualiza correctamente al modificar el valor de la vida, cierro issue.
