### ISSUE TITLE
Cargar último nivel guardado.

### ISSUE THREAD

**Issue by camilopalacios** [eloipuertas/ES2013Dimarts#270]
Estimated effort: 5 hours

Backlog: 10. As a user I want autosave feature after every completed level.

Condición de finalización: El usuario puede reanudar el juego en el último nivel desde el menú principal.

**Comment by dabami** [comment]
@camilopalacios He encontrado estas cosillas: http://whydoidoit.com/unityserializer/
http://docs.unity3d.com/Documentation/ScriptReference/PlayerPrefs.html

**Comment by camilopalacios** [comment]
Sí! También estuve leyendo lo de los PlayerPrefs. Ahí está la clave.

**Comment by Akrox** [comment]
Invalidada y Cerrada
