### ISSUE TITLE
Desenvolupar la part lògica de disparar del rifle

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#277]
Estimació: 4h

Condició de finalització: Que el rifle dispari correctament.

**Comment by casals90** [comment]
Implementació bastant avançada, ja fa mal al enemic, i dispara boles, però queda acabar de retocar alguna cosa.

**Comment by dcorto** [comment]
¡¡Nice!! :+1:

**Comment by dcorto** [comment]
@casals90, el tema de las bolitas está muy chulo y efectivamente hace impacto sobre los enemigos y los "elimina". Pero para mi gusto, faltan los siguientes items:
- Qué las bolas "exploten" al impactar sobre el enemigo. 
- Qué los proyectiles no se salgan del escenario, sino qué reboten contra los muros.
- Qué los proyectiles se "eliminen" tras X segundos si no han impactado (que no sean persistentes vaya)

¿Qué te parece?

**Comment by casals90** [comment]
@DCorto  la impelmentació es la seguent: que l'usuari dispara i la bala si toca l'enemic despareix, si toca un altre element, el travessa i desapareix. Al cap de uns 5 segons es destrueix l'objecte. Falta acabar de retocar algu encara.

**Comment by dcorto** [comment]
Ok @casals90

**Comment by casals90** [comment]
@DCorto Implementació acabada. T'explico: hi ha una variable que es diu fireRange que serveix per ajustar el temps entre dispar i dispar mentre el boto està apretat.

La lògica esta feta, l'únic, que de moment les bales no se li acaben, ja que per accedir als mètodes (ja implementats) de la classe weapon per restar bales, recarregar... necesita les animacions del rifle i per això ho he dexat així, un cop tinguem les animacions sera descomentar una linia i ja funcionara tot!

Per tant hauries de validar la part lògica pura. Gràcies!

**Comment by dcorto** [comment]
Molt bé @casals90, aquesta nit m'ho miro :)

**Comment by dcorto** [comment]
Ok @casals90 la lógica cumple con lo hablado. Te la cierro y nos centramos en la importación del modelo (y bullet) y las animaciones del arma que @Amestrmu7 ya tiene listas. Me gusta lo del modo "automático" de disparo :P
