### ISSUE TITLE
Importar model i animació del rifle

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#278]
Estimació: 2h

Condició de finalització: Quant el model del rifle i les animacions estiguin importades de manera correcta.

**Comment by casals90** [comment]
Amb l'ajuda de @Amestrmu7

**Comment by dcorto** [comment]
@casals90  aquí dejo la posición qué funciona de momento 

![screenclip](https://f.cloud.github.com/assets/5486937/1595125/04f059ca-52e6-11e3-9757-d7648c7d9aaf.png)

En el commit anterior está en esa posición.

@Amestrmu7 tendremos que mirar de afinar la posición esa contigo ya que además la animación de standby, no se visualiza el modelo, al mover los brazos hacía arriba, no se ve el modelo :P 

Por otro lado, al disparar, sale el proyectil y luego se mueve el rifle, es decir, no está sincronizado correctamente la salida del proyectil con la animación.

**Comment by ghost** [comment]
Las animaciones ya están sincronizadas y la posición del arma esta updateado a lo siguiente.
![image](https://f.cloud.github.com/assets/5486609/1595689/cda92010-52ee-11e3-82c9-98a0c91a2bcb.png)
(he re comiteado, habia aun una animación cogiendo frames de otra.)

**Comment by casals90** [comment]
@DCorto  he ajustat des d'on surt disparat el bullet, kuan puguis valida-ho i em dius el que! Gràcies

**Comment by dcorto** [comment]
@Amestrmu7 se ve el final del brazo izquierdo si el modelo lo dejamos tal y como indicas:

![image](https://f.cloud.github.com/assets/5486937/1601237/d17e6fe2-5384-11e3-8ab4-47e44d2f8618.png)

Creo que se puede ajustar un poco más :P

**Comment by dcorto** [comment]
De momento lo dejo así como indicas, hablamos y vemos que hacemos :)

**Comment by dcorto** [comment]
Falta trabajar sobre el Rifle durante el Sprint 5, mañana generaremos nuevas issues más especificas sobre el rifle para poder actuar en consecuencia durante el Sprint 5 tal y como hemos hablado durante el meeting de hoy :)

**Comment by ghost** [comment]
Esta issue esta directamente enlazada con la #285, acabo de finalizar la animación del botón. Voy a trabajar en la exportación encima de la rama del grupo A y luego se tendrá que hacer un export a la del sprint5.
@DCorto , ya casi esta para cerrar!

**Comment by dcorto** [comment]
Vale, perfecto, del merge a la branch dev-sprint5 me puedo encargar yo mismo una vez funcione todo en la rama actual Grupo-A.

Merci :)

**Comment by ghost** [comment]
Animación exportada correctamente a Unity, todo en su sitio segun los requerimientos y en sus frames!
#285  / @DCorto

**Comment by dcorto** [comment]
Movido a Sprint5, valido en breve.

**Comment by dcorto** [comment]
Bueno eso de "en breve" han sido 3 días, cierro el tema del rifle ya, sólo hay un tema del bullet qué @casals90 se tiene qué mirar. La dejo abierta hasta solucionar este tema.

:)

**Comment by casals90** [comment]
@DCorto bullet integrat i funcionanent correctament!!

**Comment by dcorto** [comment]
Ok, cerramos la issue pues
