### ISSUE TITLE
Actualizar el escudo.

### ISSUE THREAD

**Issue by dabami** [eloipuertas/ES2013Dimarts#28]
Estimated effort: 2 hours

Backlog: 14. As a user I want to see always my status on screen while I'm playing.

Condición de finalización: El escudo se actualiza cuando es modificado.

**Comment by dabami** [comment]
El escudo ya se actualiza por cada frame.

**Comment by Akrox** [comment]
Funciona, se actualiza al ser modificado el valor del escudo, cierro issue
