### ISSUE TITLE
Diseño en pantalla del Game Over: Derrota

### ISSUE THREAD

**Issue by degel99** [eloipuertas/ES2013Dimarts#281]
Estimated effort : 3h
Product Backlog: 9. As a user I want to restart at the beginning of the level when I die.
Condición de finalización: Visualización estética en pantalla del fondo de la escena y el botón para volver al inicio de la finalización del juego cuando se pierde

**Comment by Akrox** [comment]
Fondo y boton diseñados y colocados en la escena, posible reapertura en caso de mejora estetica, letras de titulo en otra issue para el siguiente sprint.
