### ISSUE TITLE
Animación del rifle (enfundar/desenfundar/disparar/recargar/melee/herido/caminar/correr/standby y acciónar botón)

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#285]
- Todas las animaciónes passan el visto bueno y son exportadas a unity y sincronizadas correctamente

Estimación: 7 horas.

**Comment by ghost** [comment]
He subido un video a youtube para que se pueda ver antes de la exportación a unity.
Espero comentarios!

http://www.youtube.com/watch?v=hRZeNynRrsY

@DCorto , falta exportarlo a unity y consider it done!

**Comment by ghost** [comment]
Falta la animación de activar botón! FAIL!

**Comment by dcorto** [comment]
La moveremos mañana al Sprint 5 para seguir con ella.

**Comment by ghost** [comment]
#278  Updated!

**Comment by ghost** [comment]
#278 finished! (updated)

**Comment by dcorto** [comment]
He movido la issue al Sprint 5. Te valido las cosas en breve.

**Comment by dcorto** [comment]
@Amestrmu7 la animación del rifle es de 33 frames 307 - 340. La de la pistola de 40 frames 240 - 280. Y no dan la misma sensación, una animación y la otra, parecen acciones diferentes. ¿Es posible hacer que la animación del rifle de Usar sea más parecida a la que se realiza con la pistola?

Gracias :)

**Comment by ghost** [comment]
Cuando tratamos el rifle estamos hablando de un mesh mas alargado en angulo Y. Si nos fijams podemos llegar a ver el brazo cortado (aun que quede bien y nadie haya visto nada raro, ahí esta). Asi que si intento alargar un poquito mas el brazo o hacer cualquier cosa mas, la animación quedará MUY cargada o incluso se verá el brazo volar si lo acerco demasiado.
Se podria re idear el "accionar botón" de otra manera, pero prefiero ver como queda con las cuchillas nuevas y la textura nueva. 
Esperaré mas comentarios por vuestra parte!
#388  #370  / @DCorto

**Comment by dcorto** [comment]
Vale, @Amestrmu7 voy a cerrar esta issue ya, no hay nada más que hacer en este sentido, las animaciones están funcionando y tal. 

Nice work.
