### ISSUE TITLE
Establecer posición por defecto del brazo y sus armas

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#287]
Actualizar el Log del juego para establecer un patrón de posición del brazo para todas las escenas. (se ha de encontrar posicionar y actualizar en las escenas disponibles)
-Condición: Esta establecido claramente las coordenadas que debe tener.

-Esfuerzo: 1h.

**Comment by ghost** [comment]
La pistola ("weapon1") deberá estar tener la configuración siguiente para estar correctamente posicionada:

Position:
x: -0.2340851    y: -0.3091784  z: 0.4382192

Rotation:
x: 0 y: 90 z: 0

Scale:
x: 25 y: 25 z: 25

(para que todos dispongan de esta información la pondré en el backlog sprint 4 Y  lo comunicaré debidamente)

**Comment by ghost** [comment]
@DCorto , esta issue esta completa. Puedes proceder al cierre. (Esta comprobado en dos escenas diferentes que dicha configuración deja a la vista el brazo bien posicionado, próximamente lo actualizaré y haré la del rifle)

**Comment by dcorto** [comment]
Ok, @Amestrmu7 acabo de verlo. Gracias. Pon la info en la wiki!
