### ISSUE TITLE
Actualizar los datos del arma equipada.

### ISSUE THREAD

**Issue by dabami** [eloipuertas/ES2013Dimarts#29]
Estimated effort: 3 hours

Backlog: 14. As a user I want to see always my status on screen while I'm playing.

Condición de finalización: La información del arma (balas en el cargador y balas totales) se actualiza correctamente.

**Comment by Akrox** [comment]
Done

**Comment by Akrox** [comment]
Bug, al momento de integrar en el proyecto dejo de funcionar la actualización de munición, hay que revisar las causas.

**Comment by Akrox** [comment]
Arreglado el bug, cierro issue
