### ISSUE TITLE
Creacio plataform monstre final

### ISSUE THREAD

**Issue by jme88** [eloipuertas/ES2013Dimarts#290]
Condicio finalització´: Creacio d'una plataforma de mida gran i que tingui textures.

estimació: 2h

**Comment by Ooin** [comment]
Fora interessant que comentessis alguna cosa mes als commits sobre el que has fet. Aixi, amb quatre pinzellades ràpides. 
Les textures encara no es veuen, aixi que de moment no tanco.

**Comment by jme88** [comment]
Oks Marc nose perque pero les textures al fer l'import no funcionen.... eliminare el projecte del blender i el tornare a fer.

**Comment by jme88** [comment]
He tornat a fer un altre cop tota la plataforma i el David m'ha dit que les textures continuen sense veures. Marc quan puguis confirma-ho. Al Cardus li passa el mateix i no entenem el que esta passant ja que ho estem fent tot com sempre.

**Comment by Ooin** [comment]
Exactament, has exportat el materials en blanc.
