### ISSUE TITLE
Rediseny de les passarel·lesdel Nivell 1

### ISSUE THREAD

**Issue by jme88** [eloipuertas/ES2013Dimarts#291]
Condicio finalització´: Redisnyar les passarel·les que apareixen al nivell 1.

Estimació: 4h

**Comment by Ooin** [comment]
Com que la iluminacio es cosa d'en @hiroCat, dona questa issue per tancada. Es veuen totes les transparencies i les colisions amb mesh renderer funcionen molt be.
