### ISSUE TITLE
Desimplementar tercera arma (a nivell lògic)

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#292]
Estimació: 1h

Condició de finalització: Quant el player nomès pugui escollir entre 2 armes (rifle i pistola).

@Dabami Desimplementem la tercera arma, tinge-ho en compte per el HUD.

**Comment by dabami** [comment]
Tomo nota! @Akrox ¿reabrimos la issue de mostrar las armas en el HUD como mejora, o que hacemos?

**Comment by casals90** [comment]
Desimplementació realitzada! @DCorto  ia pots validar quant vulguis!!

**Comment by dcorto** [comment]
Ok merci ;) Lo hago lo antes posible!

**Comment by dcorto** [comment]
Ok @casals90 falta que los chicos de HUD integren ese cambio, pero la parte de nuestro grupo está al 100%. Te cierro la issue.
