### ISSUE TITLE
Crear estructura ossos per poder animar final boss (enemic 3)

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#300]
Estimated effort: 8

Condició de finalització: El model del boss final te una estructura (bones) adequada per a poder ser animat.

**Comment by ghost** [comment]
@Amestrmu7, agafa l'issue per ajudar-me a enllestir les altres animacions.

**Comment by Xavier-RF** [comment]
Issue duplicada, ja esta tancada la issue corresponent #417
