### ISSUE TITLE
Crear deteccio de colissio entre plataforma i Player

### ISSUE THREAD

**Issue by AlcoholNahMas** [eloipuertas/ES2013Dimarts#304]
Estimacio: 5

Condicio finalitzacio: Fer que quan una plataforma estigui baixan no atravessi al player. Haig de detectar la colissio (o futura colissio) i enviar una senyal al player.

**Comment by ghost** [comment]
Esta issue ya esta implementada en el Grupo A, deberías hablar con @casals90  o @DCorto  para que te echaran una mano en este asunto. Pero creo que esta issue no es necesaria.

**Comment by AlcoholNahMas** [comment]
Amb el casals ja vai parlar i havia de crear alguna forma per enviarli un trigger quan el player estigues sota la plataforma, tot i axii ara li comentare de nou aver que te fet. Igualment el cub que envii el misatge trigger ja esta fet per si ho necesiten

**Comment by dcorto** [comment]
@AlcoholNahMas  esto está corregido, he subido una demo y todo a youtube, he comentado el bug -> https://github.com/eloipuertas/ES2013Dimarts/issues/241

**Comment by dcorto** [comment]
Falta cerrarlo por tema de terminar de probar algunos detalles que no he tenido tiempo de realizar durante el fin de semana, pero está implementado... y COMENTADO además por aquí

**Comment by AlcoholNahMas** [comment]
Perfecte, doncs dono tambe per finalitzar el bug, esta ben aconseguit que es pari i despres segueixi baixant. El proxim dia m'expliqueu com ho heu fet ja per simple curiositat.

**Comment by dcorto** [comment]
Claro, no hay problema @AlcoholNahMas. Mañana por la tarde intentaré tener un hueco e integrar en DEV todo ese tema en el Nivel1 :)

**Comment by AlcoholNahMas** [comment]
okkk!! igualment si no tens temps de posaro a DEV no et preocupis que per part de plataformes crec que ningu ha de tocar-las, l'unic que hauria de fer algo seria jo pero ja m'he mirat el codi com ho heu implementat i si tingues algun problema ja pillaria la part nova que heu implementat.

**Comment by Ooin** [comment]
Com que el problema ha estat solucionat a una altra issue tanco aquesta i la marco com a invalida.
