### ISSUE TITLE
Crear animacio del laser.

### ISSUE THREAD

**Issue by AlcoholNahMas** [eloipuertas/ES2013Dimarts#306]
Estimacio: 3

Condicio de finalitzacio: Haig de fer que quan l'usuari dispari al laser aquest es destrueixi fent el canvi de imatges corresponents.

**Comment by eloipuertas** [comment]
Pots fer el favor de crear les issues com la resta de companys, una mica de
respecte i solidaritat ajuda al treball en equip.
El dia 17/11/2013 15:58, "AlcoholNahMas" notifications@github.com va
escriure:

**Comment by AlcoholNahMas** [comment]
Que li pasa a la issue? Que esta malament? Acabo de mirar d'altres i crec que totes tenen la mateixa estructura no? Haig d'explicar mes en detall la feina que fare? @eloipuertas

**Comment by AlcoholNahMas** [comment]
Crec que ja se que ha pasat @eloipuertas. Quan he creat la issue m'he oblidat de posar la estimacio i la condicio de finalitzacio, i al cap de res, en menys de 3 min ho havia posat, si ho has vist en aquell en aquell petit temps clar que as vist la issue malament pero ja et dic pots comprovar que he tardat 3 min en canviaro. Entenc que es aixo a que et refereixes sino digam quin es el problema i ho arreglo.

**Comment by eloipuertas** [comment]
Exacte, és el format a seguir. Jo em miro les notificacions que venen del github al moment, les avaluo i contesto des del mòbil. Per això és important fer-ho bé des del principi. Pensar bé abans d'actuar.

**Comment by AlcoholNahMas** [comment]
@DCorto quan vulguis mirau si et sembla be, no et fixis en colocacio ni res, ja saps k el @DavidOrlaz s'encarrega de posaro tot al seu lloc. Adalt tens una mica d'explicacio sino preguntam el k sigui.

**Comment by dcorto** [comment]
Nice work.

PD: Te he movido la Issue al Sprint 5 y aplicado los tags correspondientes, para tenerla controlada.
