### ISSUE TITLE
Canviar els contadors dels barrils (dispars a rebre avans de destruir-se)

### ISSUE THREAD

**Issue by AlcoholNahMas** [eloipuertas/ES2013Dimarts#307]
Estimacio:1 

Condicio de finalitzacio:Canviar la variable a 3 dispars, no crec ni que es pugui considerar una issue pero ja que sempre es diu que s'ha de posar qualsevol cosa pues ho faig.

**Comment by eloipuertas** [comment]
La treva forma de treballar expressa poca responsabilitat i seriositat.
Tingues respecte pels demes i prent-te mes en serio l'assignatura.
El dia 17/11/2013 16:02, "AlcoholNahMas" notifications@github.com va
escriure:

**Comment by AlcoholNahMas** [comment]
En cap moment he volgut faltar el respecte a ningú, es una tasca que només m'afectava a mi amb lo qual no he pensat que algú li pogués molestar. Quan dic que no es pot considerar issue es perquè segon la meva opinió no era res a remarcar un canvi de variable, però com que a classe es diu sempre de comentar inclús el més petit canvi pues ho he posat com a issue. Torno a disculpar-me per si alguna persona li ha molestat i per al pròxim cop aniré amb més compte l'explicació en cap moment vull faltar al respecte als meus companys ni semblar que no em prenc seriosament l'assignatura.

**Comment by Ooin** [comment]
Funciona correctament. Despres de 3 trets el barril es destrueix.
