### ISSUE TITLE
Crear un bloc invisible per la porta del final nivell.

### ISSUE THREAD

**Issue by AlcoholNahMas** [eloipuertas/ES2013Dimarts#308]
Estimacio:3

Condicio de finalitzacio: Que quan la porta esta tancada el player no la pugui traspassar, aixo es deu a que al ser una animacio no crea els colllider, haure de crear un cub invible per fer que xoqui el player i quan s'activi la palanca destruirlo. Haure de canviar el codi dels botons/palanca.

**Comment by Ooin** [comment]
Funciona be, encara que a vegades sembla que xoquis amb un espai buit. Quan passes per la porta t'atura un instant.
Donat que funciona be et dono la issue per tancada. Ja es puliran els detall per a la demo final.
