### ISSUE TITLE
Dissenyar enemic 1: Modelatge inicial

### ISSUE THREAD

**Issue by jxaubet** [eloipuertas/ES2013Dimarts#32]
Estimated effort: 10

Condició de finalització: El modelatge amb les diferents formes geomètriques, agafa la forma del robot enemic 1.

**Comment by jxaubet** [comment]
@Xavier-RF La issue es va reobrir pel nou modelatge inicial de l'enemic 1. 
Actualment, el nou modelatge inicial ja està finalitzat (Agafa les formes geomètriques del robot pensat per a la nova versió de l'enemic 1).

**Comment by Xavier-RF** [comment]
@jordixaubet El modelatge amb les diferents formes geomètriques ja agafa la forma del robot enemic 1.

**Comment by jxaubet** [comment]
S'han afegit 5 hores més a "Estimated effort" ja que l'enemic 1 s'ha tornat a crear de nou i per tant el modelatge inicial és nou.
