### ISSUE TITLE
Create the "prototype v1 of the bullet of the Rifle"

### ISSUE THREAD

**Issue by SolrakUndel** [eloipuertas/ES2013Dimarts#325]
Estimation: 1 hours

Finishing condition: The model of the first prototype of the bullet of the Rifle must have been done, materials and textures included.

**Comment by dcorto** [comment]
Ok @SolrakUndel

![screenclip](https://f.cloud.github.com/assets/5486937/1586583/c3ea6008-522a-11e3-95af-b8d0f29df0c4.png)

Lo pruebo de importar en Unity y sustituirlo por el de pruebas para ver qué tal queda. Pero para este Sprint nos sirve seguro :)

**Comment by ghost** [comment]
Es perfecta! con el rifle de esos colores, el fondo de los otros etc. Es un proyectil que se verá bien y se entenderá que es futurista! 
GJ

**Comment by dcorto** [comment]
Ok @SolrakUndel cerramos la issue pues. He verificado el fbx. Merci.
