### ISSUE TITLE
Los sonidos del disparo del rifle tienen una "carencia" demasiado alta.

### ISSUE THREAD

**Issue by dcorto** [eloipuertas/ES2013Dimarts#329]
El sonido del disparo con rifle se repite demasiadas veces y se hace molesto.

**Comment by Nekoshido** [comment]
¿Quien ha decidido que se hace molesto? ¿@eloipuertas ?

**Comment by hiroCat** [comment]
el problema és que no s'ha canviat i encara és soroll de pistola , per al pròxim sprint agafaré un soroll d'escopeta i llestos

**Comment by dcorto** [comment]
@Nekoshido yo abrí la issue de BETA-TESTING hace 5 días, ahora creo que el comportamiento ha cambiado, pero bueno, @hiroCat ya lo mirará cuando toque según acaba de comentar.

**Comment by dcorto** [comment]
@hiroCat si ves que no hay que hacer nada, marca tú mismo esto como closed o invalid, el bug yo no lo he podido volver a reproducir en la última versión existente en "dev", la verdad, dale un vistazo y tú mismo :) 

Merci :P

**Comment by hiroCat** [comment]
esforç: 1

condició finalització : el so de l'escopeta és diferent del de la pistola
