### ISSUE TITLE
Dissenyar enemic 1: Braços (Model+Textura)

### ISSUE THREAD

**Issue by jxaubet** [eloipuertas/ES2013Dimarts#33]
Estimated effort: 3 

Condició de finalització: Crear el model dels braços i donar-los textura.

**Comment by Xavier-RF** [comment]
A finalització de l'sprint 1 encara falta la textura, issue no tancada.

**Comment by jxaubet** [comment]
S'han afegit 3 hores més a "Estimated effort" ja que l'enemic 1 s'ha tornat a crear de nou i per tant el model + textura és nou.

**Comment by jxaubet** [comment]
@Xavier-RF Condició finalitzada.

**Comment by Xavier-RF** [comment]
Issue no tancada, falta la textura ben definida i arreglar el bug #169 .

Exemple: http://www.drflail.com/images/hopper-textures.jpg

@jordixaubet

**Comment by jxaubet** [comment]
@Xavier-RF Estimated effort (millora del model + nou material/textura): 2

**Comment by jxaubet** [comment]
@Xavier-RF Condicions finalitzades.
