### ISSUE TITLE
Desenvolupar la lògica de standBy

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#330]
Estimació 1 hora

Condició de finalització: Que quant no interectuin amb el player hi hagin passat X temps, executi l'animació de StandBy

**Comment by ghost** [comment]
Si necesitas información de esto prueba a buscar "animation idle unity". Espero que sea de ayuda.

Ejemplo: http://answers.unity3d.com/questions/302318/animation-play-on-input-else-play-idle-animation.html

En este caso idle es.. mientras no se tocan botones de input, y nuestra necesidad es mientras no se toquen botones y pase x tiempo. Seria editar un poquito el codigo :p

**Comment by dcorto** [comment]
Gracias @Amestrmu7

**Comment by casals90** [comment]
@DCorto  implementacio acabada! ja pots validar quant vulguis. Cal que sapigues que hi ha una variable que es diu thresholdStandBy, que es el temps que tarda en acabar-se el StandBy, ho dic x si vols ajustar mes el temps o el que sigui a l'hora d'integrar!

**Comment by ghost** [comment]
Como el.viento casals! Ajajaa nicely done!

**Comment by dcorto** [comment]
Molt bé Jordi, després ho mirem i valido. Good work

**Comment by dcorto** [comment]
Cierro la issue, está perfecto. Simplemente dejaremos a 30 segundos la espera en lugar de los 5 actuales.
