### ISSUE TITLE
Problems with the renderization of the "prototype v1 of the Rifle" in Unity

### ISSUE THREAD

**Issue by SolrakUndel** [eloipuertas/ES2013Dimarts#331]
Estimation: 1 hours

Finishing condition: The rifle must be perfectly renderized by Unity. Right now the posterior part of the rifle shows faces that should be covered by others faces. That problem doesn't appear in Blender.

**Comment by dcorto** [comment]
@SolrakUndel ahora se ve perfecto el rifle :+1:

**Comment by dcorto** [comment]
Te cierro la issue
