### ISSUE TITLE
Nivell 2 - Creació d'una palanca 

### ISSUE THREAD

**Issue by Nekoshido** [eloipuertas/ES2013Dimarts#335]
Es crea una palanca amb la finalitat d'obrir la porta del final de nivell. Primerament creada amb la intenció de substituir el botó ja que no s'aconseguia que es modifiqués. No cal cambiar animació, ni implica a cap altre grup que no sigui el propi

Estimació: 5

Condicio finalització´: Creació 3D d'una palanca amb la finalitat de que obri la porta del final de nivell

**Comment by Ooin** [comment]
La palanca no te les mateixes textures a Unity que a Blender

**Comment by Nekoshido** [comment]
Ja ho sé, això no sé molt bé perquè va pasar, suposo que quan @hiroCat al arreglar el problema de que caigués es va desconfigurar, li vaig enviar al david les bones, però les torno a pujar

**Comment by hiroCat** [comment]
vale jo quan vaig posar la plataforma a unity es veien les textures perfectament , amb el seu on i off , ara m'ho miro
