### ISSUE TITLE
Creació de la torreta destruida

### ISSUE THREAD

**Issue by Nekoshido** [eloipuertas/ES2013Dimarts#338]
Aquesta tasca implica a en @AlcoholNahMas ja que ha de crear el codi amb el que la torreta passa d'estar sencera a estar destruida

Estimació: 6

Condicio finalització´: Creació 3D d'una torreta destruida

**Comment by dcorto** [comment]
Nice work! :)

![image](https://f.cloud.github.com/assets/5486937/1644622/eaf7b6f4-58e8-11e3-9f77-e6b57ea586e1.png)
