### ISSUE TITLE
Al recoger munición no se actualiza el HUD

### ISSUE THREAD

**Issue by dcorto** [eloipuertas/ES2013Dimarts#340]
Estimació: 3h

Al recoger un item de munición no se actualiza el HUD. El Player debe mandar un mensaje al HUD para que se actualice.

**Comment by casals90** [comment]
@DCorto vale David, revisare els mètodes del player aiam si esta el problema, si no el problema sera del HUD.

**Comment by eloipuertas** [comment]
Teniu a @dabami al grup per això mateix
El dia 27/11/2013 11:57, "Jordi" notifications@github.com va escriure:

**Comment by casals90** [comment]
@DCorto  ja pots validar!!
