### ISSUE TITLE
El item de munición sólo actualiza la munición del arma actual 

### ISSUE THREAD

**Issue by dcorto** [eloipuertas/ES2013Dimarts#341]
Al recoger un item de munición, debe actualizar el tipo de munición del tipo de item recogido, aunque esto hay que definirlo al 100% en el siguiente Sprint Review.

**Comment by casals90** [comment]
Estimacio: 3h

Condició de finalització: Quant el passa per sobre de una caixa de munició d'una arma concreta, es carregui les bales a aquesta arma i no a la atual.

**Comment by casals90** [comment]
@DCorto  ja pots validar!! juntament amb la #340.

Ja funcionen les dues issues correctament

**Comment by casals90** [comment]
Cada item de munició, se li ha de possar el tag de l'arma al qual pertany, els tags son: "municioPistola" i "municióRifle", sense això no funciona!!

**Comment by casals90** [comment]
@DavidOrlaz  alhora de posar les muncions pensa amb els tags!!

**Comment by dcorto** [comment]
Ya me encargo de eso yo. En el nivel1.

**Comment by dcorto** [comment]
Aplicados los Tags en Nivel1 para los items de Munición. @Xavier-RF ¿lo podréis aplicar vía código al dejar caer los prefabs de los enemigos?

**Comment by dcorto** [comment]
@Xavier-RF aplicados los tags en los prefabs de los items de munición. Ya lo tenemos solucionado :)
