### ISSUE TITLE
El contador de enemigos del HUD no se actualiza correctamente.

### ISSUE THREAD

**Issue by dcorto** [eloipuertas/ES2013Dimarts#343]
Estimated effort: 3 hours

Condición de finalización: El HUD muestra el número de enemigos en cada momento de forma correcta.

Comment:
En el Nivel1, aparece siempre el valor de 10 enemigos restantes independientemente del número de enemigos restantes.

**Comment by Xavier-RF** [comment]
Hay que revisar el control del numero de enemigos asi como el fin del juego cuando muera el boss

**Comment by dabami** [comment]
A ver si hoy podemos hablarlo.

**Comment by Xavier-RF** [comment]
Per tal de que no us doni problemes i pogueu matar als enemics es necessari que a la HUD camera que esta a [Player -> Main Camera -> HUD Camera] li afegiu el tag HUD Camera, sino els enemics no moriran mai.

**Comment by Xavier-RF** [comment]
Ya no hace falta sumar los enemigos con Tag Enemies al contador, ahora se añaden dos veces los enemigos que ya estan en la escena al empezar

**Comment by dcorto** [comment]
@Akrox comprueba qué no se sumen los enemigos 2 veces y ya está. En la escena Nivel1 aplicaremos el Tag en el HUD Camara como indica @Xavier-RF

**Comment by Xavier-RF** [comment]
El contador sigue sin funcionar correctamente ya que las funciones start() de los enemigos, que es donde hacen el addEnemy, se llaman antes que la función start() del hud.

Para que funcionara deberia modificarse en el script HUD.cs las dos linias siguientes:
- int numOfEnem;  ----->    int numOfEnem=0;
- numOfEnem=0;  ----->  //numOfEnem=0;

Y ya deberia funcionar correctamente

**Comment by Xavier-RF** [comment]
Doy por cerrado este problema

**Comment by camilopalacios** [comment]
Xavi, cierra también la #379 que es un duplicado invalidado de esta.
