### ISSUE TITLE
L'arma 2 pot fer desapareixer els objectes de vida i munició

### ISSUE THREAD

**Issue by Xavier-RF** [eloipuertas/ES2013Dimarts#344]
Al disparar amb l'arma 2 a un objecte de vida o munició aquest desapareix.

**Comment by casals90** [comment]
Estimació: 2h

Condició de finalització: Que quant és dispari a un objecte de tipus monició no desaparegui

**Comment by casals90** [comment]
Crec per això que el problema es que quant algun altre objecte toca la munició, desapareix, i s'hauria de canviar que simplement fos nomes el objecte player. Ja m'ho mirare

**Comment by MarcSanchez** [comment]
ja ho he arreclat, no era meva pero em calia fer-ho per quan els enemics deixen anar aquest objectes al morir. Ja que qualsevol col·lisió afectava.

**Comment by dcorto** [comment]
Gracias @MarcSanchez, cierro la issue.
