### ISSUE TITLE
Quan saltes des d'una plataforma al nivell 2 no et fas mal

### ISSUE THREAD

**Issue by Xavier-RF** [eloipuertas/ES2013Dimarts#345]
Al saltar des d'una plataforma al nivell dos el jugador no rep cap mal, encara que saltis de de la part més alta.

**Comment by casals90** [comment]
Estimació: 4h

Condició de finalització: Un cop el player rebi dany quant salti d'una plataforma de nivell 2

**Comment by casals90** [comment]
@Xavier-RF  vols dir que salta des d'una plataforma al terra? o a sobre d'una plataforma?

**Comment by Xavier-RF** [comment]
@casals90 Al saltar des de la plataforma del nivell 2 quan esta a dalt de tot al terra, el player no rep mal

**Comment by dcorto** [comment]
Creo que el bug está, en que cuando "saltas" al vacío, no te cuenta el daño. En el Nivel1, si saltas desde las plataformas superiores tampoco te haces daño.

**Comment by casals90** [comment]
@DCorto  bug corregit! He creat una escena nova (copia de "nivel1") anomenada Nivel1_provesCasals. He ajustat la variable tresholdDamageFall a 7 del script CharacterMotor.cs. I aplica el dany tant si caus sense saltar com saltant! Ia pots validar quant puguis.

**Comment by dcorto** [comment]
Ok, testeado e integrado. 

He probado saltando, dejando caer al player, de espaldas... todo OK.
