### ISSUE TITLE
Cualquier animacion nueva rompe la animacion actual.

### ISSUE THREAD

**Issue by Ooin** [eloipuertas/ES2013Dimarts#349]
Cuando se recarga, si se anda, se rompe la animacion de recargar. Y así con todas las animaciones de jugador.

**Comment by dcorto** [comment]
Gracias @Ooin aunque ya tenemos la issue reportada aquí #185.

**Comment by Ooin** [comment]
Ok, cierro esta como invalida. Como la otra no estaba en el tag de beta testing no la vi.
