### ISSUE TITLE
Dissenyar enemic 1: Cos (Model+Textura) 

### ISSUE THREAD

**Issue by jxaubet** [eloipuertas/ES2013Dimarts#35]
Estimated effort: 10

Condició de finalització: Crear el model del cos (tronc) i donar-li textura.

**Comment by Xavier-RF** [comment]
A finalització de l'sprint 1 encara falta la textura, issue no tancada.

**Comment by jxaubet** [comment]
S'han afegit 5 hores més a "Estimated effort" ja que l'enemic 1 s'ha tornat a crear de nou i per tant el model + textura és nou.

**Comment by jxaubet** [comment]
@Xavier-RF Condició finalitzada.

**Comment by Xavier-RF** [comment]
Issue no tancada, falta la textura ben definida.

Exemple: http://www.drflail.com/images/hopper-textures.jpg

@jordixaubet

**Comment by jxaubet** [comment]
@Xavier-RF Estimated effort (millora del model + nou material/textura): 3

**Comment by jxaubet** [comment]
@Xavier-RF Condicions finalitzades.
