### ISSUE TITLE
el so dels passos és incoherent mentre s'està sobre una plataforma

### ISSUE THREAD

**Issue by hiroCat** [eloipuertas/ES2013Dimarts#351]
esforç:5

condicio finalitzacio: l'usuari no escolta el soroll de desplaçament mentre està sobre una plataforma

**Comment by dcorto** [comment]
Los colliders eran muy grandes y el bullet del rifle chocaba contra ese collider y no salía de la plataforma. He reducido el tamaño del collider para que quede ajustado al suelo. He comprobado que siga detectando al player de igual modo.

![screenclip](https://f.cloud.github.com/assets/5486937/1659779/43add746-5bab-11e3-8817-6d1d501fd65b.png)
