### ISSUE TITLE
Jugabilitat: No se sap si la plataforma està activa o no mirant el botó, Caldria un efecte per saber si el botó està activat o no

### ISSUE THREAD

**Issue by eloipuertas** [eloipuertas/ES2013Dimarts#359]

**Comment by AlcoholNahMas** [comment]
D'aquesta cosa m'encarrego jo, el funcionament que he pensat seria el seguent:
(Poso la estimacio que crec jo personalment, si no hagues de posar-la la trec)
Estimacio:3
Codi finalitzacio:
-El boto desactivat estara de color vermell.
-El boto activat estara de color verd.
-Quan l'usuari estigui a una distancia en que pugui clicar el boto comensara a fer "panpallugues" de color taronja.

Per part de la palanca (que la posare per obrir la porta de final de nivell tal com us vai comentar a classe) he demanat que @Nekoshido posi a la textura un "ON" i "OFF" en gran i un color molt vistos perque es vegi clarament si esta activat o desactivat. Per suposat si us sembla be poso la palanca sino posaria un boto mes i cap problema, el que preferiu, de feina es la mateixa i ja que esta fet potser li dona una mica mes de varietat al joc.

Qualsevol canvi que vulgueu ja sabeu.

**Comment by eloipuertas** [comment]
Feu-ho i comentem resultat dimarts!
El dia 26/11/2013 20:52, "AlcoholNahMas" notifications@github.com va
escriure:

**Comment by AlcoholNahMas** [comment]
Amb aixo crec que esta solucionat el que demana aquesta issue, @DCorto quan vulguis pots comprovar el resultat. Esta tot posat a escena perque nomes hagis de provaro, no cal configurar res.

La part de la palanca esperare a que m'ho pasin. En principi allo no hauria de ser res mes que aplicar la textura i ja esta. Pero lo importan son els botons amb lo qual ja es poden testejar.

Qualsevol cosa you know.

**Comment by dcorto** [comment]
Dudas y pequeños detalles a pulir:
- La posición del botón debería respetar la ya existente, es decir, en la misma pared donde se encontraba (si no es por algún otro motivo ese cambio de lugar)
- La altura: deben estar más cerca de la altura "horizontal" del player, para el caso del primer boton a Y = -17.5 y mantener esa proporción en el resto de botones a ser posible.
- El feedback es correcto, sólo unas pequeñas cosas: 
  - Aumentar la distancia del trigger de detección, ya que el botón se puede activar a más distancia de la que el trigger de "efecto intermitente" te detecta. 
  - Por último: Si cambias el estado del botón, este sigue emitiendo el efecto intermitente mientras estás dentro del trigger, es correcto si cuando entras en el trigger no has actuado sobre el botón, pero una vez que le has cambiado el estado, debe mantenerse el botón con el color del estado activado (verde o rojo) y sólo volver ha realizar la intermitencia si sales y vuelves a entrar en el trigger. Simplemente es para no causar confusión, ya que cuando le cambias el estado, sigues dentro y al final no sabes que está pasando.

Es darle una pequeña vuelta más y estarán los botones perfectos a mi entender :)

**Comment by AlcoholNahMas** [comment]
Vale ja esta fet. vai dien els punts @DCorto :

1- El boto ja le posat al mateix lloc mes o menys, igualment no et fixis en aixo el @DavidOrlaz s'encarregara de posar tot al seu lloc depenen com o tingui dssenyat el nivell i si ha de fer canvis. (em sembla k algun canvi s'havia de fer per la jugabilitat).

2- l'altura ja le posat a -17.5 de l'eix Y. Igualment el mateix del punt 1.

3.1- He augmentat la distancia tal com deies pero tot i axi jo no la faria mes gran perque tal com es veu en el joc queda molt fals/extrany que pugui activar el boto quan es veu k la ma no arriba. Osigui es lleig realment, crec k es millor que el player s'acosti una mica mes (encara k no hagi de fero) per a que l'animacio de la ma quedi be. Pero si vols es posa encara mes gran.

3.2- Esta canviat i comprovat. Ara funciona tal com volies, ara kuan clices el boto el color es queda fix, i fins que no tapartes i et tornes a acostar no fa el efecte intermitent. Queda millor s'ha de reconeixer ;)

**Comment by dcorto** [comment]
Ok, @AlcoholNahMas te comento:

1- Ok :)
2- Perfecto. 
3.1 - Le he reducido al Player la distancia de actuación del botón para forzar a usarlo en dentro del trigger que se ha colocado, he estado haciendo 10 min pruebas y está funcionando muy bien. Sólo cuando "entras" en diagonal dentro del trigger hace un poco el "tonto" pero es algo ya más difícil de solucionar técnicamente debido a que el trigger es rectangular y tal, pero bueno, de no tener nada de feedback a tener esto, es un gran avance, ahora sí que mola el botón.
3.2 - Es perfecto :)

Una última cosa (es para @DavidOrlaz básicamente) cuando pongas los botones definitivos a partir de este inicial, sobretodo que el trigger, siempre tenga la misma distancia, porqué sino el player activará el trigger y seguramente no "active" el botón. Aunque es fácil revisar este comportamiento una vez esten todos en su posición final, mejor tenerlo ya desde ahora en mente.

![screenclip](https://f.cloud.github.com/assets/5486937/1627496/0178c33e-56f3-11e3-9cb8-b50b77d242d5.png)

**Comment by dcorto** [comment]
@AlcoholNahMas prueba de hacer un poco más ancho el trigger y mira si puedes reproducir lo que te comento de que no te detecta cuando entras en "diagonal" hacía el botón, así se podría mitigar un poco ese efecto. Aunque vamos, lo más lógico es actuar sobre el botón de cara :P Pero si le das un poco más de anchura al trigger, vemos qué tal.

Mañana lo acabamos de rematar. Great work :)

**Comment by AlcoholNahMas** [comment]
He canviat per una esfera deformada el trigger. Aixo es el millor que he pogut aconseguir perke les diagonals mestan matan. Hi ha una csa molt rara i es k a la mateixa distancia si clices el boto estan a la dreta d'ell s'activa pero si estas a leskerra del boto no. Aixo pot ser algo de la cameras? Ara puju el resultat

**Comment by dcorto** [comment]
@AlcoholNahMas en principio veo que el trigger finalmente como hablamos es el inicial, de forma rectangular ahora mismo.(es correcto) El feedback del botón está muy bien conseguido.

Vídeo de demo -> http://www.youtube.com/watch?v=51ADR6bx-Oc&feature=youtu.be
