### ISSUE TITLE
No es veu que l'enemic (1) llanci cap projectil, simplement es veu que fa algo amb els braços raro. 

### ISSUE THREAD

**Issue by eloipuertas** [eloipuertas/ES2013Dimarts#361]

**Comment by Xavier-RF** [comment]
Es pot afegir un efecte laser o un efecte de particules al disparar l'enemic

**Comment by Xavier-RF** [comment]
Esforç: 8 hores

Condició de finalització: Ll'enemic shooter mostri algun efecte a l'hora de disparar

**Comment by Xavier-RF** [comment]
@hiroCat Condició de finalització complerta
