### ISSUE TITLE
Les boles de l'enemic(2) no es poden esquivar o destruir, sempre acabes rebent, tot i que mori l'enemic

### ISSUE THREAD

**Issue by eloipuertas** [eloipuertas/ES2013Dimarts#362]

**Comment by MarcSanchez** [comment]
Meva! Ja esta el codi fet, issue #310, funciona per tots els projectils d'aquest tipus tot i que a la issue només digués el boss final.

**Comment by Xavier-RF** [comment]
A classe hem comentat de fer que les boles no persegueixin, siguin més rapides i facin un efecte com d'explosió i mal d'area.

**Comment by Xavier-RF** [comment]
Esforç: 4 hores

Condició de finalització: Modificar el funcionament dels missils eprseguidors per a que no persegueixin, siguin més rapides i facin un efecte com d'explosió i mal d'area.
