### ISSUE TITLE
Crear builds per Linux i Mac Universals

### ISSUE THREAD

**Issue by eloipuertas** [eloipuertas/ES2013Dimarts#364]
Per a que funcioni en arquitectures de 32 i 64 bits.

Edit:

Estimación de esfuerzo: 1h
Condición de finalización: Una vez las builds finales del Sprint5 sean completamente universales (x86 y x64) en los 3 sistemas operativos.

**Comment by jme88** [comment]
La build de windows, para windows x32 no funciona.

**Comment by dcorto** [comment]
Ya la tengo fixeado, merci!
