### ISSUE TITLE
El salt del robot és molt petit, no arriba ni a sortir de la plataforma mòbil quan s'és molt a prop de la plataforma

### ISSUE THREAD

**Issue by eloipuertas** [eloipuertas/ES2013Dimarts#366]

**Comment by casals90** [comment]
Estimacio: 2h

Condició de finalització: Quant la configuració del salt estigui correcte, es a dir, que puguis arribar correctament a la distància de salt de les plataformes.

Amb @DavidOrlaz

**Comment by dcorto** [comment]
¿Chicos con esto que hay que hacer?

A nivel personal, creo que el salto del jugador está correcto. No hace falta tocarlo más. ¿Qué opinas @DavidOrlaz?

**Comment by casals90** [comment]
@DCorto crec que això, s'hauria de provar directa sobre l'escenari final, i alla acabar d'ajustar les variable de salt de CharacterMotor.cs: 

![img](https://f.cloud.github.com/assets/5485780/1672742/29eebf9a-5cd8-11e3-8e6a-df26ff0480e0.png)

**Comment by DavidOrlaz** [comment]
He vist el salt i crec que com diu @DCorto el salt està ja bé. No hi ha problemes per sortir o entrar a les plataformes ara que es paren uns segons abans de retornar enrere.
