### ISSUE TITLE
Testing en ArchLinux 64Bits, No apareix cap caràcter en la HUD. Quina Font s'està fent servir? 

### ISSUE THREAD

**Issue by eloipuertas** [eloipuertas/ES2013Dimarts#367]

**Comment by camilopalacios** [comment]
He hecho el build para:

PC, Mac & Linux Standalone
Target platform: Windows
Architecture: x86_64

He ejecutado en Ubuntu 13.04 y se ve corre HUD, menús, escenas, etc.

**Comment by dcorto** [comment]
Cuando haga las builds al cerrar el sprint las haré universales :)

**Comment by camilopalacios** [comment]
OK! quería decir correcto\*  Por cierto, el ubuntu es 64bit.

**Comment by dcorto** [comment]
Pues @camilopalacios cierra tú mismo este issue si ya has comprobado el funcionamiento correcto tan solo generando builds universales. 

Mercii

**Comment by camilopalacios** [comment]
Se lo he dicho a @Akrox y la cerrará él. :)

**Comment by Akrox** [comment]
Cierro issue.
