### ISSUE TITLE
Estant situat sobre la plataforma mòbil i mirant al botó de la part posterior, l'arma dispara però no fa efecte visual

### ISSUE THREAD

**Issue by eloipuertas** [eloipuertas/ES2013Dimarts#368]
Estimación Esfuerzo: 1h
Condición Finalización: Una vez el muzzle se visualize por encima del entorno con la misma prioridad que el modelo del Player

**Comment by dcorto** [comment]
Simplemente era añadir el layer "Ignore Raycast" que usa el muzzle a la cámara "Guns" que pinta el modelo del player.
