### ISSUE TITLE
L'arma 2 no es veu ben renderitzada, hi ha un tros volant.

### ISSUE THREAD

**Issue by eloipuertas** [eloipuertas/ES2013Dimarts#369]

**Comment by ghost** [comment]
M'assigno l'issue, encara que l'error pot venir des d'una textura mal formada fins a una animació mal exportada.
S'analitzarà correctament i s'obrirà un issue per explicar el problema i la solució.

**Comment by SolrakUndel** [comment]
Em parlat @Amestrmu7 i jo i s'ha pensar en fer una millora de la textura de les espases per la meva part i un canvi d'angle de les espases per part de @Amestrmu7 per poderles intuir més.

**Comment by ghost** [comment]
Editadas las cuchillas para hacer mas visible su mesh.
Las entradas nuevas estan en #388 #285.
