### ISSUE TITLE
Quan tens la segona arma, el botó e, fa atac secundari en comptes d'actuar.

### ISSUE THREAD

**Issue by eloipuertas** [eloipuertas/ES2013Dimarts#370]

**Comment by ghost** [comment]
Aquest bug ha sorgit per la falta de la animació de "apretar el botó" al rifle. 

#285 no és tancada i faltaria implementar l'animació del botó amb el rifle i exportar-ho correctament a unity.

**Comment by dcorto** [comment]
Cerramos esto, lo tenemos corregido ya con la issue #285.
