### ISSUE TITLE
En el segon nivell els enemics et poden disparar, però no saps qui t'està acribillant

### ISSUE THREAD

**Issue by eloipuertas** [eloipuertas/ES2013Dimarts#371]
Estimated effort: 4 hours

Condición de finalización: El HUD cambia a un tono rojo cuando el jugador recibe un impacto o se hace daño.

**Comment by ghost** [comment]
Una possible idea de solució seria implementar una llum tipus làser, que sortís dels enemics quan et disparessin. (És una proposta, no ha de ser el resultat final)

**Comment by camilopalacios** [comment]
Alfonso y yo nos pondremos a trabajar para que el HUD cambie cuando el jugador recibe un impacto.

**Comment by camilopalacios** [comment]
He querido poner @Amestrmu7 .

**Comment by camilopalacios** [comment]
@Amestrmu7 y yo hemos testeado hoy esta issue y la damos por finalizada.

**Comment by camilopalacios** [comment]
Esperamos el visto bueno del tester.
