### ISSUE TITLE
Diseño del texto en la Pantalla de Victory

### ISSUE THREAD

**Issue by degel99** [eloipuertas/ES2013Dimarts#376]
Estimated effort : 3h
Product Backlog: 9. As a user I want to restart at the beginning of the level when I die.
Condición de finalización: Visualización estética en pantalla del texto informativo que se muestra al jugador cuando gana el juego.

**Comment by Akrox** [comment]
Se visualiza correctamente la nueva fuente de la escena de victoria en color verde oscuro
