### ISSUE TITLE
Diseño: Estética del Menú Opciones

### ISSUE THREAD

**Issue by degel99** [eloipuertas/ES2013Dimarts#377]
Estimated effort : 4h
Product Backlog: 11. As a user I want to start a new game or continue at the beginning of the last level I played.
Condición de finalización: Visualización estética del diseño del menú de opciones: fondo con botones

**Comment by SolrakUndel** [comment]
- Actualización: Cambiado el personal asignado a mi mismo.
  - Motivo: soy el nuevo componente de diseño del grupo E, está issue queda ahora a mi cargo.

**Comment by Akrox** [comment]
Colocada un diseño de fondo en la escena opciones, muy chulo y en colores.
