### ISSUE TITLE
Diseño del texto en la Pantalla de Game Over

### ISSUE THREAD

**Issue by degel99** [eloipuertas/ES2013Dimarts#378]
Estimated effort : 3h
Product Backlog: 9. As a user I want to restart at the beginning of the level when I die.
Condición de finalización: Visualización estética en pantalla del texto informativo que se muestra al jugador cuando pierde el juego.

**Comment by Akrox** [comment]
Cambiada la fuente del texto en escena gameover y con un color rojo oscuro.
