### ISSUE TITLE
Reduir el numero de triangles que te el monstre final.

### ISSUE THREAD

**Issue by jme88** [eloipuertas/ES2013Dimarts#380]
Esforç: 2 hores

Condició de finalització: Reduir el número de polígons que te el monstre final per a que no i hagi problemes amb el unity.

**Comment by jme88** [comment]
Per a reduir el poligons aqui explica com es fa:
http://wiki.blender.org/index.php/Doc:2.6/Manual/Modifiers/Generate/Decimate

**Comment by jme88** [comment]
Els exports a unity no estan fets nomes he tocat l'arxiu del blender.

**Comment by Xavier-RF** [comment]
@jme88 dono la issue per acabada, l'export a unity s'ha de fer quan estiguin fetes les animacions
