### ISSUE TITLE
Creació de l'animació de la caixa de munició pel rifle

### ISSUE THREAD

**Issue by Nekoshido** [eloipuertas/ES2013Dimarts#385]
Estimacion tiempo: 1
Condición de finalización: Creació, aplicació i visualització de l'animació en el joc

**Comment by ghost** [comment]
(perdon!!, he linkeado mal un comentario! (he puesto 385 y era 285 xD) )

**Comment by dcorto** [comment]
@Nekoshido hace un par de días que vi la animación, @DavidOrlaz las tiene que colocar. Una vez esté todo en Unity te cierro esto. Pero en blender estaba ok :)

**Comment by dcorto** [comment]
Perfecto, está funcionando.
