### ISSUE TITLE
Reduir el nombre de triangles que té l'enemic 4

### ISSUE THREAD

**Issue by jxaubet** [eloipuertas/ES2013Dimarts#386]
Esforç: 2 hores

Condició de finalització: Reduir el nombre de polígons que té l'enemic 4 per a que no hi hagi problemes amb el Unity.

**Comment by jme88** [comment]
Marc aqui trovaras com fer per reduir el poligons:
 http://wiki.blender.org/index.php/Doc:2.6/Manual/Modifiers/Generate/Decimate

Despres de fer el boolean i eliminar el cubs no visibles de l'enemic pot aplicar aixo.
Hem de anar amb compte a l'hora de eliminar poligons amb el booelan ja que si elimines poligons que a simple vista no es veuen pot ser que a l'hora de animar el enemic aquets poligons si que es vegin.

**Comment by jme88** [comment]
Marc com hem parlat faig meva la issue.

**Comment by jme88** [comment]
Els exports a unity no estan fets nomes he tocat l'arxiu del blender.

**Comment by Xavier-RF** [comment]
Al model amb el nombre de poligons reduït no es veu correctament la cara de l'enemic.

**Comment by jme88** [comment]
Oks, llavors el monstre tindrà mes polígons, ja el modificaré per a que es vegi be la cara.
