### ISSUE TITLE
Programar la plataforma perquè sigui mes facil per el player pujar i baixar de la plataforma

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#387]
Estimació: 2h

Condició de finalització: Fer que quant la platafroma arribi a la alçada mínima, estigui parada durant 2 segons, i quant estigui a l'alçada màxima es pari durant 2 segons, així facilita que el player pugui pujar i baixa mes facilment.

**Comment by dcorto** [comment]
@casals90 esto lo cierro, @AlcoholNahMas lo remató hace unos días. Y la marco como "inválid" para que no tenerla que contabilizar en el sprint planning.
