### ISSUE TITLE
Importar l'animació de "usar boton" i la nova animació de correr de l'arma 2 i sincronitzar-la amb les altres

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#388]
Estimació: 3h

Condició de finalització: Quant totes les animacions estiguin importades i sincronitzades correctament

**Comment by ghost** [comment]
Estoy trabajando otra vez en ello para corregir la issue #406, de todas maneras acabo de subir una nueva version del  correr junto a la de apretar el botón. Deberias pasarte por github para verlas!
Compruevalo y dejame tus comentarios! ( #285 )

**Comment by ghost** [comment]
Bytheway, esta issue seria mas de mi parte, ya que soy el encargado de importarlas a unity y todo lo que conlleva ello!
Te parece bien que me asignes esta issue a mi? Gracias!

**Comment by casals90** [comment]
Vale perfetce @Amestrmu7 estem en contacte

**Comment by dcorto** [comment]
@Amestrmu7 asignate la issue, no creo que haya problema, si estás trabajando con ella tú mismo :)
