### ISSUE TITLE
Ajustar el tir parabòlic de la bullet de l'arma 2

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#389]
Estimació: 2h

Condició de finalització: Quant el tir parabòlic de la bullet estigui sincronitzat amb la mirilla que hi ha a la pantalla

**Comment by casals90** [comment]
@DCorto he creat una escena nova que es diu grup_Objecte_Player_Casals i alla estic treballant! el bullet ja l'he importat i es dispara correctament. Falta arreglar alguna coseta!

**Comment by dcorto** [comment]
@casals90 ok ya me dices cuando esté al 100%. Por mi parte le he añadido el código al bullet.cs para que también el barril (y el cañon láser) reciban daño desde el bullet. Y te he corregido la escena: he aplicado el Layer Gun al brazo del rifle ya que penetraba en los muros.

En relación estricta la issue, ciertamente, el bullet va más ajustado a la posición del crosshair. Nice work

**Comment by casals90** [comment]
@Dabami  ara funciona correctament, pero hi haun problema amb el HUD, kuan es mort un enemic, la funcio "sendMessage" del enemic cap al HUD, per notificar que hi ha un enemic menys no funciona,

**Comment by dcorto** [comment]
Lo del HUD ya lo tenemos controlado. Cierro la issue. Good job
