### ISSUE TITLE
Diseño hud: mostrar arma y munición

### ISSUE THREAD

**Issue by degel99** [eloipuertas/ES2013Dimarts#39]
Estimated effort : 2h
Product Backlog: 14. As a user I want to see always my status on screen while I'm playing.
Condición de finalización: Visualización de las dos primeras armas en fondo blanco (se activa la que está en uso) y la munición (bala) del personaje

**Comment by Akrox** [comment]
Cierro ya que cumple su condicion de finalización, estan puestas en el HUD, y funcionan correctamente al seleccionarlas, puede ser reabierta para una mejora en el diseño.
