### ISSUE TITLE
Col·locar els nous botons corregits

### ISSUE THREAD

**Issue by DavidOrlaz** [eloipuertas/ES2013Dimarts#398]
Estimació: 1h
Condició de finalització: Haver col·locat els botons que s'han corregit a la issue #359 en el mateix lloc que els anteriors.

**Comment by dcorto** [comment]
Ya los puedes colocar :)

**Comment by dcorto** [comment]
@DavidOrlaz el trigger de los botones es demasiado "grande", es decir, detecta al player antes de que este pueda accionar el botón. Hay que reducir un poco el trigger. 

En la escena EscenaGroup_Objecte_Personatge además están funcionando ya las plataformas. Simplemente prueba de ajustar el tamaño de los trigger en las "X" a tú criterio para reducir el tamaño lo más ajustado posible.

**Comment by DavidOrlaz** [comment]
Por más pequeño que haga el trigger siempre veo una pequeña zona donde no puedes pulsar. Si reduzco el trigger simplemente podrás apretar más tarde, pero seguirá existiendo esa zona.

**Comment by dcorto** [comment]
@DavidOrlaz el IgnoreRaycast es la clave :)  ¡Ya lo tenemos casi cerrao este tema también! Nice work

**Comment by dcorto** [comment]
Perfecto @DavidOrlaz.

Nice work
