### ISSUE TITLE
Col·locar les plataformes corregides

### ISSUE THREAD

**Issue by DavidOrlaz** [eloipuertas/ES2013Dimarts#399]
Estimació: 2h
Condició de finalització: Haver col·locat les plataformes que s'han corregit en el mateix lloc que les anteriors.

**Comment by dcorto** [comment]
Cuando pongas las plataformas finales, recuerda de que solamente, las plataformas que deben "aplastar" al Player deben tener el compontente RigidBody. Qué me lo he encontrado en plataformas dónde no necesitan ese componente

![screenclip](https://f.cloud.github.com/assets/5486937/1639248/63d17b96-581c-11e3-96db-37d6bcac3ac7.png)

**Comment by dcorto** [comment]
@DavidOrlaz en "EscenaGroup_Objecte_Personatge" ya están las plataformas posicionadas y con las posiciones finales aplicadas, lo necesitaba hacer para poder probar el tema de los botones.

Dale un repaso a qué todo funcione no vaya a ser que se me haya colado algo. 

Gracias :)

**Comment by dcorto** [comment]
Nice work, perfecto.
