### ISSUE TITLE
Opción de configuración de teclado.

### ISSUE THREAD

**Issue by dabami** [eloipuertas/ES2013Dimarts#4]
Estimated effort: 3 hours

Backlog: 1. As a user I want to control a robot with a configurable keyboard.

Condición de finalización: El usuario es capaz de configurar los controles para cada acción del personaje.

**Comment by dabami** [comment]
He visto que el Unity crea una pantalla antes de iniciar el juego para cambiar la configuración gráfica y de teclado, con lo que esta issue quedaría resuelta automáticamente. 

¿Lo damos por bueno o igualmente meto una opción dentro del juego, lo cual sería un poco innecesario?

Edit: bueno, la cosa seria cambiar el imput manager para que aparezcan las acciones que nos interesan, pero entonces nada de poner una opción en el menú. No se, a ver que os parece.

**Comment by camilopalacios** [comment]
Probemos la opción de Unity a ver que tal queda, si no, seguimos con el plan original.

**Comment by dcorto** [comment]
Team E una cosa, a ver, sobre los inputs, por defecto hay en Unity esto:

![screenclip](https://f.cloud.github.com/assets/5486937/1300976/32fcdc86-311b-11e3-9422-dce1ada18082.png)

Se supone según la Wiki ( https://github.com/eloipuertas/ES2013Dimarts/wiki/Controles) que hay que cambiar los nombres esos en inglés por los que hay definidos en la Wiki así pues:

"Jump", debería llamarse "Saltar".

No sé si habéis hecho ese cambio ya vosotros en vuestro proyecto de Unity :P

**Comment by dabami** [comment]
No, nosotros no tenemos que hacer ese cambio, en principio, hasta el segundo sprint (es decir, la opción de menú). Podéis usar los nombres de la wiki y si creeis que falta algo podéis añadirlo.

**Comment by dcorto** [comment]
Vale todo aclarado. Gracias!

**Comment by dcorto** [comment]
@Dabami le he cambiado el nombre a los 2 primeros inputos por Horizontal y Vertical (en la wiki), qué así da más énfasis de que se trata de los ejes de movimiento :) Y además Unity ya los identifica así esos 2 casos en concreto.

**Comment by dabami** [comment]
Ok, no problem @DCorto .

**Comment by dabami** [comment]
Invalido la Issue, ya no se hará.

**Comment by Akrox** [comment]
Invalidada y Cerrada
