### ISSUE TITLE
Col·locar barrils a l’escena

### ISSUE THREAD

**Issue by DavidOrlaz** [eloipuertas/ES2013Dimarts#400]
Estimació: 1h
Condició de finalització: Haver col·locat un parell de barrils a l'escena.

**Comment by dcorto** [comment]
@DavidOrlaz cuando puedas, recuerda de colocar los barriles en "EscenaGroup_Objecte_Personatge" para que pueda integrarlos en Nivel1. Merci :)

**Comment by dcorto** [comment]
Integrados en nivel1 correctamente.
