### ISSUE TITLE
Col·locar noves municions per a les dues armes a l’escena

### ISSUE THREAD

**Issue by DavidOrlaz** [eloipuertas/ES2013Dimarts#401]
Estimació: 1h
Condició de finalització: Haver col·locat municions de les dues armes per tota l'escena.

**Comment by dcorto** [comment]
David, ya puedes colocar estos items y asi vemos qué tal quedan y puedo cerrarle a Hector todas sus issues.

**Comment by dcorto** [comment]
@casals90 @AlcoholNahMas falta que le pongáis el código a cada objeto de este tipo de items en la escena "EscenaGroup_Objecte_Personatge".

**Comment by dcorto** [comment]
Lo mismo para el item de Salud, no hace nada, le falta el script asociado. ¿Qué ha pasado @DavidOrlaz?

**Comment by MarcSanchez** [comment]
@DavidOrlaz hauríes de col·locar els objectes cura i municio de la carpeta resources, els he creat amb la script asociada per fer que els enemics els deixin anar al morir. Així t'estalviaras de posar la script per cada objecte. Si s'arrecla #413, s'hauria de refer el prefab, tingues-ho/tingueu-ho en compte.

**Comment by Xavier-RF** [comment]
Ja estan creats els prefabs del item de curació i de les dues municions

**Comment by dcorto** [comment]
@Xavier-RF merci ya los he colocado en Nivel1 en las posiciones que @DavidOrlaz ha marcado.

@MarcSanchez así lo he hecho :)
