### ISSUE TITLE
Corregir el angulo de inclinación de las cuchillas del rifle para que se aprecien mejor

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#406]
Condition: 
-Las cuchillas estan bien colocadas y da una sensación distinta a la inicial.
-Exportado a unity correctamente

Esfuerzo:
-2horas

**Comment by dcorto** [comment]
@Amestrmu7 mira lo que comento aquí -> #268

**Comment by dcorto** [comment]
Te cierro esto @Amestrmu7 :)
