### ISSUE TITLE
Implementar el daño hecho por los barriles.

### ISSUE THREAD

**Issue by dabami** [eloipuertas/ES2013Dimarts#407]
Estimated effort: 3 hours

31 - As a CPU player I want to place explosive barrels that fires when receives an amount of damage and it causes injuries to human player if he is next to.

Condición de finalización: Los barriles, al explotar, hacen daño al jugador.

**Comment by dcorto** [comment]
@Dabami lo veo perfecto. Para acabar de matarlo, te importa renombrar el script a "codiBarril.cs" y si puedes generar un "prefab" para qué sea más fácil montarlo en la escena. ¿Please?

**Comment by dabami** [comment]
@DCorto, hecho. Si necesitas algo mas, dilo.

**Comment by dcorto** [comment]
Completado :)
