### ISSUE TITLE
Al saltar repetidamente encima de un "secuaz" de un enemigo, te pasas el juego

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#408]
- Como dice el enunciado, si se salta repetidamente encima de un enemigo sale el cartel de "HAS ESCAPADO". No deberia ser asi!

dejo un video de muestra! siento que se vea todo lo demás!

https://www.youtube.com/watch?v=MEuGRHeALyA

**Comment by dcorto** [comment]
Es debido a que el Player muere :P

**Comment by ghost** [comment]
FAIL!
