### ISSUE TITLE
El "cos" de les caixes de municio queda molt per sota de l'objecte que veiem.

### ISSUE THREAD

**Issue by MarcSanchez** [eloipuertas/ES2013Dimarts#413]
És dificil colisionar-hi, ja que si les caixes estan posicionades al terra, el cos quedarà per sota i no hi podrem col·lisionar

**Comment by MarcSanchez** [comment]
http://imgur.com/VMND41X

aixi es veu mes clar, el cos del objecte es aquell punt verd petit a sota. Nomes desapareixera si hi colisionem. Per aixo les caixes situades amb antel·lació al terra no desapareixen.

@DavidOrlaz o @AlcoholNahMas ?

**Comment by dcorto** [comment]
@MarcSanchez quizás es más tema de Blender, no lo sé al 100%. 

Gracias por comentarnos con detalle el problema. En el meeting de hoy vamos a comentar el problema y asignaremos un responsable para solucionar el issue. 

Merci

**Comment by Xavier-RF** [comment]
Ja esta arreglat aquest problema i estan afegit els 2 prefabs necessaris per a que els enemics tirin munició i vida quan morin.

@MarcSanchez @DavidOrlaz @DCorto

**Comment by dcorto** [comment]
Nice!
