### ISSUE TITLE
Modelatge ordinadors

### ISSUE THREAD

**Issue by MCardus** [eloipuertas/ES2013Dimarts#414]
Esforç estimat: 3

Condició de finalització: Modelar i texturitzar uns ordinadors, perquè puguin ser colocats als nivells i donar mes joc a la IA. Issue comentat previament amb en @DavidOrlaz  i grup NPC

**Comment by Xavier-RF** [comment]
El models d'ordinador estan acabats. De moment no han estat afegits a l'escena.
