### ISSUE TITLE
Quant es mort un enemic i és resta de la part del HUD el joc dexia de funcionar

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#416]
Estimacio: 2

Condició de finalització: Que quant es mori un enemic, es resti en la part del HUD correctament

**Comment by dabami** [comment]
Creo que @Akrox está en ello. #343

**Comment by dcorto** [comment]
Esto lo ha comentado @Xavier-RF, aquí también -> #343 

¿Qué hacemos con este tema? Creo que ya lo tenemos solucionado. Yo no he podido reproducir el bug comentado por @casals90

**Comment by dcorto** [comment]
@Dabami,  ¿esto ya no pasa verdad? Por lo menos yo no consigo reproducir el bug...

**Comment by dabami** [comment]
Exacto, he estado testeandolo y ya está arreglado.

**Comment by dcorto** [comment]
Perfecto, gracias ;)
