### ISSUE TITLE
Rig (osos) del boss final

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#417]
-Condició:  Els osos del boss permeten la trancisió de les animacions amb fluidesa.
                El mesh pot ser treballat (doblegat, girat, etc) amb facilitat.

-Esforç: 2hores.

**Comment by ghost** [comment]
Como bien pone en el commit, al seleccionar el peso de los mesh para su debida animación se colapsan en si mismos.
Se tienen que hacer secciones de Meshes (por ejemplo la cabina y lo que la envuelve deberia ser un solo mesh ( a no ser que queramos que se abra etc))
@jme88 o @jordixaubet, podriais poneros en contacto ? 
Gracias

**Comment by jxaubet** [comment]
@Amestrmu7 Lo miro cuanto antes y te aviso

**Comment by ghost** [comment]
Sigue teniendo el modifier de mirror (con lo que el problema aun persiste), deberias arreglarlo lo mas pronto posible @jordixaubet.

**Comment by ghost** [comment]
He intentado aplicar un bone mirror para evitar el problema ese, al hacer Control + J, las propiedades de los mesh se han vuelto locas y los pesos se han "trasladado" a otros meshes sin querer. estoy intentando encontrar una solucion.

**Comment by ghost** [comment]
Consider it done! @Xavier-RF , pots comprovar (crec que ja ho hem fet per skype) que els osos estan en les posicions correctes i que els mesh-weights estan correctes.
