### ISSUE TITLE
Millorar animacions enemic urpes

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#422]
Esforç estimat: 2

Condició de finalització: Millorar en general el comportament del model, revisar les deformacions dels poligons en NPC.

**Comment by Xavier-RF** [comment]
L'animació d'atac es encara més ràpida que la de l'sprint anterior. Haurien de ser com a minim 15 frames per animació, sino no es veu bé. He modificat la velocitat de reproducció de l'animació d'atac desde Unity per a que es pugui veure.
