### ISSUE TITLE
Els enemics d'eixaran d'estar inactius despres de rebre mal.

### ISSUE THREAD

**Issue by MarcSanchez** [eloipuertas/ES2013Dimarts#425]
Un cop rebin mal per part del jugador, els enemics no seguiran quiets.

Esforç estimat: 2

Condició de finalització, els enemics no deixaran d'atacar al jugador un cop han rebut mal encara que aquest s'allunyi. També seran capaços de rebre mal

**Comment by Xavier-RF** [comment]
S'hauria de fer que els enemics summoner també fessin aixo pero amb l'atac homing, que només invoquin quan el player esta aprop i llencin missils si esta lluny sense desactivarse

@MarcSanchez
