### ISSUE TITLE
Diseño hud: escudo y vida

### ISSUE THREAD

**Issue by degel99** [eloipuertas/ES2013Dimarts#43]
Estimated effort : 3h
Product Backlog: 14. As a user I want to see always my status on screen while I'm playing
Condición de finalización: Visualización de la imagen de vida y escudo del personaje

**Comment by degel99** [comment]
El diseño del escudo totalmente acabado (2h), con un color característico de fondo que es el verde, se pensó en este ya que el de la vida sería rojo (la cruz típica que representaría la vida).

**Comment by Akrox** [comment]
Done
