### ISSUE TITLE
Torreta Laser faci mal

### ISSUE THREAD

**Issue by AlcoholNahMas** [eloipuertas/ES2013Dimarts#433]
Estimacio: 3 
Condicio finalitzacio: Que el player rebi mal quan traspassi/xoqui/doni contra un laser (la part vermella llarga).

Fare un trigger que detecti kuan el player esta dintre del laser i cridi la funcio del player de rebre mal. Posare el valor de mal que ha de fer el laser com a variable publica aixi poseu la que volgueu. Lo de destruir el alser i tal es una altre issue i es seguira poden destruir

**Comment by AlcoholNahMas** [comment]
@DCorto Kuan vulguis mirau, pero hi ha coses k no van perke algu deu estar tocan coses del joc i no van, almenys els botons no van ara, i el laser no resta la vida al player, osigui li resta perke veig k epr consola li resta pero ala pantalla no es posa

**Comment by dcorto** [comment]
@AlcoholNahMas  no van cosas porqué la escena en la que estás trabajando está obsoleta, elimina la escena EscenaGroup_Objecte_Personatge_GERARD y sustitúyela por una copia de Nivel1 actual.

**Comment by dcorto** [comment]
Otra cosa, estas usando una variable publica -> public GameObject Player;

Que es mala idea, para obtener el player mejor hacerlo así:

GameObject Player;

y en el método Start():

void Start () {
        player = GameObject.FindGameObjectWithTag("Player");
    }

De lo contrario, hay que estar "bindeando" desde el Unity el Player a mano a cada cambio de objeto.

**Comment by AlcoholNahMas** [comment]
Val, fai els canvis de codi i utilitzo la escena del nivell1 k dius k ho havia fet tot a la meva escena. NO to miris encara, ja tavisare kuan tingui els canvis fets

**Comment by AlcoholNahMas** [comment]
@DCorto Ara ja he fet els canvia k ams demanat, i funciona be el joc i tot.

**Comment by dcorto** [comment]
Vale, perfecto @AlcoholNahMas. Lo voy integro ya mismo en Nivel1. Y te cierro la issue en breve. Nice work

**Comment by dcorto** [comment]
DEMO -> http://www.youtube.com/watch?v=o4jAa3-_ZjU&feature=youtu.be
