### ISSUE TITLE
Animació enemic final (caminar i atac melee)

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2013Dimarts#436]
- La animació sobre el mesh de l'enemic final ha de ser fluida i les transicions han de ser efectives per evitar un mal "gameplay".
- Les animacións son agradables a la vista i tenen una velocitat correcta
  -Importació de les animacións a unity es satisfactori

Esforç: 2h.

**Comment by ghost** [comment]
Falta la exportació a l'escena de unity! M'hi poso ara!

**Comment by Xavier-RF** [comment]
Ja esta afegida a Unity la animació
