### ISSUE TITLE
Diseño hud: Icono y contador de enemigo

### ISSUE THREAD

**Issue by degel99** [eloipuertas/ES2013Dimarts#44]
Effort Time: 4h
Product Backlog: 14. As a user I want to see always my status on screen while I'm playing.
Condición de finalización: Visualización de la imagen del icono de enemigo con su contador

**Comment by Akrox** [comment]
Icono temporal de enemigos en el HUD.

**Comment by degel99** [comment]
Por el momento al no tener un rostro el enemigo, el icono sigue siendo el actual y los números también

**Comment by Akrox** [comment]
Sigue pendiente modificación de rostro del enemigo, quedara para otro sprint

**Comment by SolrakUndel** [comment]
- Actualización: Cambiado el personal asignado a mi mismo.
  - Motivo: soy el nuevo componente de diseño del grupo E, está issue queda ahora a mi cargo.

**Comment by Akrox** [comment]
Imagen final funcionando
