### ISSUE TITLE
Crear un splash per al videojoc

### ISSUE THREAD

**Issue by jme88** [eloipuertas/ES2013Dimarts#441]
Estimated effort : 1h
Condición de finalización: Diseñar un splash per al joc amb el nom del videojoc.

**Comment by dcorto** [comment]
Gracias @jme88 ya lo he aplicado.

![screenclip](https://f.cloud.github.com/assets/5486937/1688140/c8f681ca-5e01-11e3-9d34-3ac9275f704d.png)

**Comment by Xavier-RF** [comment]
El slpash ja esta afegit al joc per @DCorto

**Comment by dcorto** [comment]
En MAC no se verá ya que hay un bug reportado en Unity 4.2.2 -> http://forum.unity3d.com/threads/204905-Bug-in-unity-4-2-2-Missing-splash-image-and-icons

Está fixeado en 4.3 pero no vamos a estas alturas subir de versión de Unity. 

Por lo menos en Windows se verá :)

**Comment by jme88** [comment]
Oks, si puedo ayudar en algo mas decidmelo.
