### ISSUE TITLE
Mostrar los datos de las armas (equipadas o no).

### ISSUE THREAD

**Issue by dabami** [eloipuertas/ES2013Dimarts#6]
Estimated effort: 2 hours.

Backlog: 14. As a user I want to see always my status on screen while I'm playing.

Condición de finalización: En el hud se muestra la información del arma equipada (balas en el cargador y balas totales) y las pestañas que indican qué slot está seleccionado (1,2 o 3).

**Comment by dabami** [comment]
@camilopalacios  Cambio en la estimación de las horas para el sprint 3: de 3 a 2 horas

**Comment by Akrox** [comment]
Done
