### ISSUE TITLE
Atac a distància i cos a cos dels NPCs

### ISSUE THREAD

**Issue by MarcSanchez** [eloipuertas/ES2013Dimarts#65]
Condició de validació: Els npcs han de ser capaços de atacar cos a cos i a distància al personatge principal.

Temps estimat 8h

**Comment by Xavier-RF** [comment]
L'animació de l'atac a distancia encara no esta creada, de moment utilitzem l'animació d'ajupir-se per substituir-la.

@MarcSanchez @aforasca7
