### ISSUE TITLE
Creation of the prototype  "v1" of "Mesh of the gun"

### ISSUE THREAD

**Issue by SolrakUndel** [eloipuertas/ES2013Dimarts#66]
Estimation: 5 hours

Finishing condition: Create the firts prototype of the gun's mesh (first weapon of the player) that can fit into the player's hand. The result must have mesh, materials and textures.

**Comment by dcorto** [comment]
![2013-10-24 17 58 54](https://f.cloud.github.com/assets/5486937/1400461/3384e526-3cc5-11e3-997d-7cc8370fa1ee.png)

Cierro la issue, todo cumple la condición de finalización y además Jordi ha podido importarla para ir probando.
