### ISSUE TITLE
Dar funcionalidad al Menú de Pause

### ISSUE THREAD

**Issue by camilopalacios** [eloipuertas/ES2013Dimarts#74]
Estimated effort: 5 hours
Product Backlog: 11. As a user I want to start a new game or continue at the beginning of the last level I played.
Validation: All the options from the Pause Menu do their task.

**Comment by Akrox** [comment]
Funciona genial

**Comment by Akrox** [comment]
Hay que cambiar el nombre del boton "Salir a Windows" por algo más apropiado.

**Comment by camilopalacios** [comment]
He detectado un bug al abrir el menu y cerrarlo con pause, el cursor se queda habilitado.

**Comment by Akrox** [comment]
Arreglado bug
