### ISSUE TITLE
Crear el bloqueo de la puerta de entrada.

### ISSUE THREAD

**Issue by dabami** [eloipuertas/ES2013Dimarts#77]
Estimated effort: 1 hour.

6- As a user I want to have one point of entry and only one point of exit for each room.

Condición finalización: El usuario no es capaz de pasar por la puerta de entrada del nivel.

**Comment by dabami** [comment]
@Akrox He creado un bloque invisible que se tiene que poner en la entrada para que el personaje no pueda pasar. Puedes testearlo con el nivel 1.

**Comment by dabami** [comment]
Invalido la Issue, ya no hace falta.

**Comment by Akrox** [comment]
Invalidada y Cerrada
