### ISSUE TITLE
Info messages during the game

### ISSUE THREAD

**Issue by camilopalacios** [eloipuertas/ES2013Dimarts#78]
Estimated effort: 4 hours
Product Backlog: 35. As a user I want some info messages during the game to help me.
Validation: The info messages are shown in-game in the first level.

**Comment by Akrox** [comment]
Genial, funcionan muy bien

**Comment by Akrox** [comment]
Agregar más mensajes.

**Comment by Akrox** [comment]
Nuevos mensajes agregados (Se volvera a abrir si hacen falta más mensajes de ayuda)
