### ISSUE TITLE
Crear model del braç esquerre del personatge principal

### ISSUE THREAD

**Issue by SolrakUndel** [eloipuertas/ES2013Dimarts#8]
Estimated effort: 4.5 hours

Finishing condition: Arm mesh shall be completed (an arm from shoulder to hand, both included), with materials and textures done too.

**Comment by ghost** [comment]
Demasiados polígonos, muy complejo. 
Si observamos la animación el hombro no se llegaria a ver.
Edit\* El modelo es una mano derecha, ahora mismo estoy trabajando en ello, voy a hacerle un mirror y trabajare en ello
Edit2: Unity Free tiene como maximo 65.000 poligonos para un solo MESH. Si este brazo tiene...22.524.. hay que bajar esa cantidad de poligonos para que el juego sea mas "light". Asi que voy a dejar este import para cuando este Fixed.

**Comment by SolrakUndel** [comment]
Yep, my fault, I'll mirror it, delete the shoulder and put a simple sphere as a shoulder (that will make the mesh be more like the armature, so the 3D rotation of the arm to the shoulder will be possible), maybe add some minor change.

**Comment by dcorto** [comment]
Cierro el issue, el modelo está realizado :+1:
