### ISSUE TITLE
Diseño logo

### ISSUE THREAD

**Issue by degel99** [eloipuertas/ES2013Dimarts#81]
Estimated effort: 2 hours.
Product Backlog: 11. As a user I want to start a new game or continue at the beginning of the last level I played.
Condición de finalización: Identificación personalizada para el juego

**Comment by degel99** [comment]
Por ahora se diseño el logo en bosquejo, con las iniciales del juego (BU) unas flechas que las rodean (símbolo de una actualización que hace referencia al Upgrade) y de fondo un diseño de fuego activo (símbolo de algo caótico que no siguió las reglas de la actualización: Badass).

**Comment by Akrox** [comment]
Done
