### ISSUE TITLE
Diseño en pantalla del Game Over: Victoria

### ISSUE THREAD

**Issue by degel99** [eloipuertas/ES2013Dimarts#87]
Estimated effort : 3h
Product Backlog: 9. As a user I want to restart at the beginning of the level when I die.
Condición de finalización: Visualización estética en pantalla del fondo de la escena y el botón para volver al inicio de la finalización del juego cuando se gana.

**Comment by Akrox** [comment]
Diseños de fondo y boton de volver creados y puestos en su sitio, queda pendiente el diseño de las letras en otra issue para el siguiente sprint.
