### ISSUE TITLE
Mapejar tots els controls per jugar

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#9]
Estimació 4 hores

Finalització: Quant l'usuari pugui moure el personatge endavant, enrera, pels costats a través de teclat

**Comment by dabami** [comment]
¿Deberíamos ponernos de acuerdo con el nombre de cada input o eso es cosa de los integradores?

Pd: soy el que configura el inputManager.

**Comment by dcorto** [comment]
Lo mejor es poner en la wiki los controles con los nombres del mapeo y la función y asi todos lo sabemos.

**Comment by dcorto** [comment]
Dabami, no te he respondido antes realmente, lo hago ahora: Sí, evidentemente hay que ponerse de acuerdo antes y luego ya vemos como integrarlo.

http://docs.unity3d.com/Documentation/Manual/Input.html 

Según la docu hay ya los mappings predefinidos: 

Every project has the following default input axes when it's created:

Horizontal and Vertical are mapped to w, a, s, d and the arrow keys.
Fire1, Fire2, Fire3 are mapped to Control, Option (Alt), and Command, respectively.
Mouse X and Mouse Y are mapped to the delta of mouse movement.
Window Shake X and Window Shake Y is mapped to the movement of the window.

Ahora sólo falta:
- Definir cuantas teclas / botones necesitamos
- Darles un nombre único (para identificarlos dentro de los scripts) 
- Darles una descripción (más genérica) para el panel de configuración :)

Lo voy mirando también con Jordi durante el día de hoy :)

Hablamos!

**Comment by dabami** [comment]
Vale, si, eso es lo que vi anoche.

En realidad ya lo tenemos definido, solo tengo que darle un nombre a cada acción, asignarle unas teclas por defecto y una descripción (configurar el InputManager, vamos). Ahora lo pondré en la wiki todo y cuando lo tenga hecho ya actualizaré el InputManager.asset

;)

**Comment by dcorto** [comment]
Vale, pues cuando tengas eso en la wiki, lo comentas, así Jordi C. que tiene que programar el movimiento lo podrá aplicar :)

**Comment by dabami** [comment]
Mapa de controles en la wiki, si hay alguna duda ya sabéis.

**Comment by dcorto** [comment]
@casals90 la condición de finalización de la issue, debería ser algo como: "Mapear los controles según la Wiki siguientes: Lateral, Avanzar-retroceder, Disparar... etc" 

 Los que se necesiten para este Sprint 1 y así podré validar correctamente :)

**Comment by dcorto** [comment]
@casals90 ya tienes el mapeo:

![screenclip](https://f.cloud.github.com/assets/5486937/1302109/bfc55208-312d-11e3-8c80-da84fdf72095.png)

En Unity -> Edit -> Project Settings -> Inputs

**Comment by dcorto** [comment]
Faltaba definir el input Agacharse :P fixed!

**Comment by casals90** [comment]
El personatje es mou correcatment: recta, dreta, esquerra i enrerra. També amb el mouse es mou tant amunt i avall com dreta i esquerra.

**Comment by dcorto** [comment]
Cerramos issue!
