### ISSUE TITLE
Ocultar el puntero del mouse ingame.

### ISSUE THREAD

**Issue by dcorto** [eloipuertas/ES2013Dimarts#91]
Estimación de esfuerzo: 0.5h

Condición de finalización: Una vez el el puntero del mouse no sea visible mientras el jugador está en la partida. (Debe seguir apareciendo en el menú de pausa u otros menús)

**Comment by dcorto** [comment]
@casals90 verifica que todos los datos de dicho bug estén correctos, creo que sí

**Comment by casals90** [comment]
Bug corregit

**Comment by casals90** [comment]
@DCorto  ia pots validar el bug!

**Comment by dcorto** [comment]
Perfecto :)
