### ISSUE TITLE
Suavizar la velocidad de movimiento del personaje (cámara)

### ISSUE THREAD

**Issue by dcorto** [eloipuertas/ES2013Dimarts#92]
Estimación de esfuerzo: 0.5h

Condición de finalización: Una vez el movimiento del personaje (la cámara) sea más suave.

**Comment by casals90** [comment]
@DCorto  bug arregalt. He fet servir un script d'una versio vella i l'he modificat per tal que la sensibilitat del mouse sigui mes lenta. 
Ja pots validar quant et vagi be!

**Comment by dcorto** [comment]
@casals90 perfecto! Simplemente he ajustado un poquito más la sensibilidad y el retraso del movimiento:
-  float mouseSensitivity = 1.5f;
-  float mouseSensitivity = 2.5f;

y
-  float moveTime = 0.1f;
-  float moveTime = 0.05f;

0.1 de moveTime me daba sensación de "lag" al mover el mouse.

Te cierro el issue!
