### ISSUE TITLE
Mejorar el campo de visión de la cámara

### ISSUE THREAD

**Issue by dcorto** [eloipuertas/ES2013Dimarts#93]
Estimación de esfuerzo: 1h

Problema: El campo de visión es demasiado cerrado.

Condición de finalización: Una vez el campo de visión sea más amplio.

**Comment by dcorto** [comment]
@casals90 faltaría conocer la estimación de este bug. Please! :)

**Comment by casals90** [comment]
Estimació: 1h

**Comment by dcorto** [comment]
Ok, issue actualizada. Merci!

**Comment by casals90** [comment]
@DCorto  ia pots validar aquest bug

**Comment by dcorto** [comment]
Correcto, ahora la el campo de visión es más amplio y realmente da una sensación más real dentro del escenario. Good job!
