### ISSUE TITLE
Creation of the prototype "v2" of "Mesh of the Left/Right Arm"

### ISSUE THREAD

**Issue by SolrakUndel** [eloipuertas/ES2013Dimarts#95]
Estimation: 4 hours

Finishing condition: Create the second prototype of the left and right arms' meshes (left: melee weapon/ right: main mesh for all the other weapons) from elbow to fingers including both. The result must have mesh, materials and textures.

**Comment by ghost** [comment]
Muy bueno la estructura final, pasar de 25.000 polígonos a 1200 incrementando la calidad del brazo es espectacular.
Gran trabajo Carlos! Great job there! Keep going!

**Comment by dcorto** [comment]
Good job @SolrakUndel :+1:
