### ISSUE TITLE
Improve "Low-poly" creation skills

### ISSUE THREAD

**Issue by SolrakUndel** [eloipuertas/ES2013Dimarts#97]
Estimation: 4 hours

Finishing condition: I must have improve my skills making "low-poly" meshes, I must use results of my other issues as witnesses.

**Comment by dcorto** [comment]
![screenclip](https://f.cloud.github.com/assets/5486937/1385177/6b1b848e-3b5a-11e3-8e65-8dacebcbe4a4.png)

Queda patente la reducción de poligonos, de unos 20K las primeras versiones a 2K! Good job! :)
