### ISSUE TITLE
Preparar el projecte per treballar (fer el pull, crear un escenari de prova...) 

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#98]
Estimació: 1h

Condicio de finalització: Un cop estigui el projecte apunt per seguir treballant, i hi hagi un escenari nou per desenvolupar en aquest sprint

**Comment by casals90** [comment]
@Amestrmu7  issue finalitzada!

**Comment by dcorto** [comment]
Hahaha @casals90  qué el tester soy yoo! :P:P:P:P:P 

Ya he visto los cambios en los directorios, ahora da gusto verlo todo organizado :)

Good job!
