### ISSUE TITLE
Crear gestio de armes bàsiques

### ISSUE THREAD

**Issue by casals90** [eloipuertas/ES2013Dimarts#99]
Estimació: 3h

Condició de finalització: Un cop les classes i els seus mètodes estiguin desenvolupades, es puguin canviar les tres armes a traves de teclat, i també desenvolupada la lògica de recarrega i gestió de bales.

User story: 24

**Comment by casals90** [comment]
@DCorto  ja pots validar!

Tota la logica de les bales i de recarregar ja esta implementada! nomes falta inegrar el model! a l'espera de @Amestrmu7  que tingui l'animació!

**Comment by ghost** [comment]
Hoy mismo intento tener algo para que puedas pre visualizarlo, de todas maneras deberias intentar buscar por google o donde sea si a tus raycast se les puede asignar una velocidad y un mesh (para poner una bala que no sea velocidad luz).

**Comment by dcorto** [comment]
Esta issue la cerraremos cuando la #105 esté también al 100% ya que así tenemos las 2 atadas. @casals90 ya he visto todo el desarrollo, está muy bien.

**Comment by dcorto** [comment]
Estoy probando el markdown de listas de tareas ^^! :P
- [x] logica del arma1
- [x] logica del arma2
- [x] logica del arma3
- [x] logica del arma4

https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments <- nos puede ser útil para algunas cosas usar esto :)
